// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::digest_outbox_type::DigestOutbox;

/// Table handle for the table `digest_outbox`.
///
/// Obtain a handle from the [`DigestOutboxTableAccess::digest_outbox`] method on [`super::RemoteTables`],
/// like `ctx.db.digest_outbox()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.digest_outbox().on_insert(...)`.
pub struct DigestOutboxTableHandle<'ctx> {
    imp: __sdk::TableHandle<DigestOutbox>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `digest_outbox`.
pub struct DigestOutboxTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for DigestOutboxTableAccessor {
    type Row = DigestOutbox;
    type Handle<'db> = DigestOutboxTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.digest_outbox()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `digest_outbox`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DigestOutboxTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DigestOutboxTableHandle`], which mediates access to the table `digest_outbox`.
    fn digest_outbox(&self) -> DigestOutboxTableHandle<'_>;
}

impl DigestOutboxTableAccess for super::RemoteTables {
    fn digest_outbox(&self) -> DigestOutboxTableHandle<'_> {
        DigestOutboxTableHandle {
            imp: self.imp.get_table::<DigestOutbox>("digest_outbox"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DigestOutboxInsertCallbackId(__sdk::CallbackId);
pub struct DigestOutboxDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for DigestOutboxTableHandle<'ctx> {
    type Row = DigestOutbox;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = DigestOutbox> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for DigestOutboxTableHandle<'ctx> {
    type Row = DigestOutbox;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = DigestOutbox> + '_ { self.imp.iter() }

    type InsertCallbackId = DigestOutboxInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DigestOutboxInsertCallbackId {
        DigestOutboxInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DigestOutboxInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DigestOutboxDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DigestOutboxDeleteCallbackId {
        DigestOutboxDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DigestOutboxDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for DigestOutboxTableHandle<'ctx> {
    type InsertCallbackId = DigestOutboxInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DigestOutboxInsertCallbackId {
        DigestOutboxInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DigestOutboxInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for DigestOutboxTableHandle<'ctx> {
    type DeleteCallbackId = DigestOutboxDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DigestOutboxDeleteCallbackId {
        DigestOutboxDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DigestOutboxDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DigestOutboxUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DigestOutboxTableHandle<'ctx> {
    type UpdateCallbackId = DigestOutboxUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DigestOutboxUpdateCallbackId {
        DigestOutboxUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DigestOutboxUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for DigestOutboxTableHandle<'ctx> {
    type UpdateCallbackId = DigestOutboxUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DigestOutboxUpdateCallbackId {
        DigestOutboxUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DigestOutboxUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `outbox_id` unique index on the table `digest_outbox`,
        /// which allows point queries on the field of the same name
        /// via the [`DigestOutboxOutboxIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.digest_outbox().outbox_id().find(...)`.
        pub struct DigestOutboxOutboxIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<DigestOutbox, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> DigestOutboxTableHandle<'ctx> {
            /// Get a handle on the `outbox_id` unique index on the table `digest_outbox`.
            pub fn outbox_id(&self) -> DigestOutboxOutboxIdUnique<'ctx> {
                DigestOutboxOutboxIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("outbox_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> DigestOutboxOutboxIdUnique<'ctx> {
            /// Find the subscribed row whose `outbox_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<DigestOutbox> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<DigestOutbox>("digest_outbox");
    _table.add_unique_constraint::<u64>("outbox_id", |row| &row.outbox_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DigestOutbox>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<DigestOutbox>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `DigestOutbox`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait digest_outboxQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `DigestOutbox`.
            fn digest_outbox(&self) -> __sdk::__query_builder::Table<DigestOutbox>;
        }

        impl digest_outboxQueryTableAccess for __sdk::QueryTableAccessor {
            fn digest_outbox(&self) -> __sdk::__query_builder::Table<DigestOutbox> {
                __sdk::__query_builder::Table::new("digest_outbox")
            }
        }

