// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::digest_subscription_type::DigestSubscription;

/// Table handle for the table `digest_subscription`.
///
/// Obtain a handle from the [`DigestSubscriptionTableAccess::digest_subscription`] method on [`super::RemoteTables`],
/// like `ctx.db.digest_subscription()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.digest_subscription().on_insert(...)`.
pub struct DigestSubscriptionTableHandle<'ctx> {
    imp: __sdk::TableHandle<DigestSubscription>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `digest_subscription`.
pub struct DigestSubscriptionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for DigestSubscriptionTableAccessor {
    type Row = DigestSubscription;
    type Handle<'db> = DigestSubscriptionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.digest_subscription()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `digest_subscription`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DigestSubscriptionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DigestSubscriptionTableHandle`], which mediates access to the table `digest_subscription`.
    fn digest_subscription(&self) -> DigestSubscriptionTableHandle<'_>;
}

impl DigestSubscriptionTableAccess for super::RemoteTables {
    fn digest_subscription(&self) -> DigestSubscriptionTableHandle<'_> {
        DigestSubscriptionTableHandle {
            imp: self.imp.get_table::<DigestSubscription>("digest_subscription"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DigestSubscriptionInsertCallbackId(__sdk::CallbackId);
pub struct DigestSubscriptionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for DigestSubscriptionTableHandle<'ctx> {
    type Row = DigestSubscription;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = DigestSubscription> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for DigestSubscriptionTableHandle<'ctx> {
    type Row = DigestSubscription;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = DigestSubscription> + '_ { self.imp.iter() }

    type InsertCallbackId = DigestSubscriptionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DigestSubscriptionInsertCallbackId {
        DigestSubscriptionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DigestSubscriptionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DigestSubscriptionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DigestSubscriptionDeleteCallbackId {
        DigestSubscriptionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DigestSubscriptionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for DigestSubscriptionTableHandle<'ctx> {
    type InsertCallbackId = DigestSubscriptionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DigestSubscriptionInsertCallbackId {
        DigestSubscriptionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DigestSubscriptionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for DigestSubscriptionTableHandle<'ctx> {
    type DeleteCallbackId = DigestSubscriptionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DigestSubscriptionDeleteCallbackId {
        DigestSubscriptionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DigestSubscriptionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DigestSubscriptionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DigestSubscriptionTableHandle<'ctx> {
    type UpdateCallbackId = DigestSubscriptionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DigestSubscriptionUpdateCallbackId {
        DigestSubscriptionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DigestSubscriptionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for DigestSubscriptionTableHandle<'ctx> {
    type UpdateCallbackId = DigestSubscriptionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DigestSubscriptionUpdateCallbackId {
        DigestSubscriptionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DigestSubscriptionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `subscription_id` unique index on the table `digest_subscription`,
        /// which allows point queries on the field of the same name
        /// via the [`DigestSubscriptionSubscriptionIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.digest_subscription().subscription_id().find(...)`.
        pub struct DigestSubscriptionSubscriptionIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<DigestSubscription, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> DigestSubscriptionTableHandle<'ctx> {
            /// Get a handle on the `subscription_id` unique index on the table `digest_subscription`.
            pub fn subscription_id(&self) -> DigestSubscriptionSubscriptionIdUnique<'ctx> {
                DigestSubscriptionSubscriptionIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("subscription_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> DigestSubscriptionSubscriptionIdUnique<'ctx> {
            /// Find the subscribed row whose `subscription_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<DigestSubscription> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<DigestSubscription>("digest_subscription");
    _table.add_unique_constraint::<u64>("subscription_id", |row| &row.subscription_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DigestSubscription>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<DigestSubscription>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `DigestSubscription`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait digest_subscriptionQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `DigestSubscription`.
            fn digest_subscription(&self) -> __sdk::__query_builder::Table<DigestSubscription>;
        }

        impl digest_subscriptionQueryTableAccess for __sdk::QueryTableAccessor {
            fn digest_subscription(&self) -> __sdk::__query_builder::Table<DigestSubscription> {
                __sdk::__query_builder::Table::new("digest_subscription")
            }
        }

