// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct IngestInbox {
    pub ingest_id: u64,
    pub kind: String,
    pub payload: String,
    pub submitted_by: __sdk::Identity,
    pub is_processed: bool,
    pub last_error: String,
    pub created_at: __sdk::Timestamp,
    pub processed_at: i64,
}


impl __sdk::InModule for IngestInbox {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `IngestInbox`.
///
/// Provides typed access to columns for query building.
pub struct IngestInboxCols {
    pub ingest_id: __sdk::__query_builder::Col<IngestInbox, u64>,
    pub kind: __sdk::__query_builder::Col<IngestInbox, String>,
    pub payload: __sdk::__query_builder::Col<IngestInbox, String>,
    pub submitted_by: __sdk::__query_builder::Col<IngestInbox, __sdk::Identity>,
    pub is_processed: __sdk::__query_builder::Col<IngestInbox, bool>,
    pub last_error: __sdk::__query_builder::Col<IngestInbox, String>,
    pub created_at: __sdk::__query_builder::Col<IngestInbox, __sdk::Timestamp>,
    pub processed_at: __sdk::__query_builder::Col<IngestInbox, i64>,
}

impl __sdk::__query_builder::HasCols for IngestInbox {
    type Cols = IngestInboxCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        IngestInboxCols {
            ingest_id: __sdk::__query_builder::Col::new(table_name, "ingest_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            payload: __sdk::__query_builder::Col::new(table_name, "payload"),
            submitted_by: __sdk::__query_builder::Col::new(table_name, "submitted_by"),
            is_processed: __sdk::__query_builder::Col::new(table_name, "is_processed"),
            last_error: __sdk::__query_builder::Col::new(table_name, "last_error"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            processed_at: __sdk::__query_builder::Col::new(table_name, "processed_at"),

        }
    }
}

/// Indexed column accessor struct for the table `IngestInbox`.
///
/// Provides typed access to indexed columns for query building.
pub struct IngestInboxIxCols {
    pub ingest_id: __sdk::__query_builder::IxCol<IngestInbox, u64>,
    pub kind: __sdk::__query_builder::IxCol<IngestInbox, String>,
}

impl __sdk::__query_builder::HasIxCols for IngestInbox {
    type IxCols = IngestInboxIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        IngestInboxIxCols {
            ingest_id: __sdk::__query_builder::IxCol::new(table_name, "ingest_id"),
            kind: __sdk::__query_builder::IxCol::new(table_name, "kind"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for IngestInbox {}

