// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::ingest_inbox_type::IngestInbox;

/// Table handle for the table `ingest_inbox`.
///
/// Obtain a handle from the [`IngestInboxTableAccess::ingest_inbox`] method on [`super::RemoteTables`],
/// like `ctx.db.ingest_inbox()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ingest_inbox().on_insert(...)`.
pub struct IngestInboxTableHandle<'ctx> {
    imp: __sdk::TableHandle<IngestInbox>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `ingest_inbox`.
pub struct IngestInboxTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for IngestInboxTableAccessor {
    type Row = IngestInbox;
    type Handle<'db> = IngestInboxTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.ingest_inbox()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ingest_inbox`.
///
/// Implemented for [`super::RemoteTables`].
pub trait IngestInboxTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`IngestInboxTableHandle`], which mediates access to the table `ingest_inbox`.
    fn ingest_inbox(&self) -> IngestInboxTableHandle<'_>;
}

impl IngestInboxTableAccess for super::RemoteTables {
    fn ingest_inbox(&self) -> IngestInboxTableHandle<'_> {
        IngestInboxTableHandle {
            imp: self.imp.get_table::<IngestInbox>("ingest_inbox"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct IngestInboxInsertCallbackId(__sdk::CallbackId);
pub struct IngestInboxDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for IngestInboxTableHandle<'ctx> {
    type Row = IngestInbox;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = IngestInbox> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for IngestInboxTableHandle<'ctx> {
    type Row = IngestInbox;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = IngestInbox> + '_ { self.imp.iter() }

    type InsertCallbackId = IngestInboxInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IngestInboxInsertCallbackId {
        IngestInboxInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IngestInboxInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = IngestInboxDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IngestInboxDeleteCallbackId {
        IngestInboxDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IngestInboxDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for IngestInboxTableHandle<'ctx> {
    type InsertCallbackId = IngestInboxInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IngestInboxInsertCallbackId {
        IngestInboxInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IngestInboxInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for IngestInboxTableHandle<'ctx> {
    type DeleteCallbackId = IngestInboxDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IngestInboxDeleteCallbackId {
        IngestInboxDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IngestInboxDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct IngestInboxUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for IngestInboxTableHandle<'ctx> {
    type UpdateCallbackId = IngestInboxUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IngestInboxUpdateCallbackId {
        IngestInboxUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IngestInboxUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for IngestInboxTableHandle<'ctx> {
    type UpdateCallbackId = IngestInboxUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IngestInboxUpdateCallbackId {
        IngestInboxUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IngestInboxUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `ingest_id` unique index on the table `ingest_inbox`,
        /// which allows point queries on the field of the same name
        /// via the [`IngestInboxIngestIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.ingest_inbox().ingest_id().find(...)`.
        pub struct IngestInboxIngestIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<IngestInbox, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> IngestInboxTableHandle<'ctx> {
            /// Get a handle on the `ingest_id` unique index on the table `ingest_inbox`.
            pub fn ingest_id(&self) -> IngestInboxIngestIdUnique<'ctx> {
                IngestInboxIngestIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("ingest_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> IngestInboxIngestIdUnique<'ctx> {
            /// Find the subscribed row whose `ingest_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<IngestInbox> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<IngestInbox>("ingest_inbox");
    _table.add_unique_constraint::<u64>("ingest_id", |row| &row.ingest_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<IngestInbox>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<IngestInbox>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `IngestInbox`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait ingest_inboxQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `IngestInbox`.
            fn ingest_inbox(&self) -> __sdk::__query_builder::Table<IngestInbox>;
        }

        impl ingest_inboxQueryTableAccess for __sdk::QueryTableAccessor {
            fn ingest_inbox(&self) -> __sdk::__query_builder::Table<IngestInbox> {
                __sdk::__query_builder::Table::new("ingest_inbox")
            }
        }

