// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkOutboxDeliveredArgs {
    pub outbox_id: u64,
}

impl From<MarkOutboxDeliveredArgs> for super::Reducer {
    fn from(args: MarkOutboxDeliveredArgs) -> Self {
        Self::MarkOutboxDelivered {
            outbox_id: args.outbox_id,
}
}
}

impl __sdk::InModule for MarkOutboxDeliveredArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_outbox_delivered`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_outbox_delivered {
    /// Request that the remote module invoke the reducer `mark_outbox_delivered` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`mark_outbox_delivered:mark_outbox_delivered_then`] to run a callback after the reducer completes.
    fn mark_outbox_delivered(&self, outbox_id: u64,
) -> __sdk::Result<()> {
        self.mark_outbox_delivered_then(outbox_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `mark_outbox_delivered` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn mark_outbox_delivered_then(
        &self,
        outbox_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl mark_outbox_delivered for super::RemoteReducers {
    fn mark_outbox_delivered_then(
        &self,
        outbox_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(MarkOutboxDeliveredArgs { outbox_id,  }, callback)
    }
}

