// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkIngestFailedArgs {
    pub ingest_id: u64,
    pub error: String,
}

impl From<MarkIngestFailedArgs> for super::Reducer {
    fn from(args: MarkIngestFailedArgs) -> Self {
        Self::MarkIngestFailed {
            ingest_id: args.ingest_id,
            error: args.error,
}
}
}

impl __sdk::InModule for MarkIngestFailedArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_ingest_failed`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_ingest_failed {
    /// Request that the remote module invoke the reducer `mark_ingest_failed` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`mark_ingest_failed:mark_ingest_failed_then`] to run a callback after the reducer completes.
    fn mark_ingest_failed(&self, ingest_id: u64,
error: String,
) -> __sdk::Result<()> {
        self.mark_ingest_failed_then(ingest_id, error,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `mark_ingest_failed` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn mark_ingest_failed_then(
        &self,
        ingest_id: u64,
error: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl mark_ingest_failed for super::RemoteReducers {
    fn mark_ingest_failed_then(
        &self,
        ingest_id: u64,
error: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(MarkIngestFailedArgs { ingest_id, error,  }, callback)
    }
}

