// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ReceiptItem {
    pub receipt_item_id: u64,
    pub receipt_id: u64,
    pub product_name: String,
    pub quantity: f64,
    pub unit: String,
    pub price: f64,
    pub currency: String,
    pub matched_item_id: u64,
}


impl __sdk::InModule for ReceiptItem {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ReceiptItem`.
///
/// Provides typed access to columns for query building.
pub struct ReceiptItemCols {
    pub receipt_item_id: __sdk::__query_builder::Col<ReceiptItem, u64>,
    pub receipt_id: __sdk::__query_builder::Col<ReceiptItem, u64>,
    pub product_name: __sdk::__query_builder::Col<ReceiptItem, String>,
    pub quantity: __sdk::__query_builder::Col<ReceiptItem, f64>,
    pub unit: __sdk::__query_builder::Col<ReceiptItem, String>,
    pub price: __sdk::__query_builder::Col<ReceiptItem, f64>,
    pub currency: __sdk::__query_builder::Col<ReceiptItem, String>,
    pub matched_item_id: __sdk::__query_builder::Col<ReceiptItem, u64>,
}

impl __sdk::__query_builder::HasCols for ReceiptItem {
    type Cols = ReceiptItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ReceiptItemCols {
            receipt_item_id: __sdk::__query_builder::Col::new(table_name, "receipt_item_id"),
            receipt_id: __sdk::__query_builder::Col::new(table_name, "receipt_id"),
            product_name: __sdk::__query_builder::Col::new(table_name, "product_name"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            unit: __sdk::__query_builder::Col::new(table_name, "unit"),
            price: __sdk::__query_builder::Col::new(table_name, "price"),
            currency: __sdk::__query_builder::Col::new(table_name, "currency"),
            matched_item_id: __sdk::__query_builder::Col::new(table_name, "matched_item_id"),

        }
    }
}

/// Indexed column accessor struct for the table `ReceiptItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct ReceiptItemIxCols {
    pub receipt_id: __sdk::__query_builder::IxCol<ReceiptItem, u64>,
    pub receipt_item_id: __sdk::__query_builder::IxCol<ReceiptItem, u64>,
}

impl __sdk::__query_builder::HasIxCols for ReceiptItem {
    type IxCols = ReceiptItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ReceiptItemIxCols {
            receipt_id: __sdk::__query_builder::IxCol::new(table_name, "receipt_id"),
            receipt_item_id: __sdk::__query_builder::IxCol::new(table_name, "receipt_item_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ReceiptItem {}

