// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RecipeIngredient {
    pub recipe_ingredient_id: u64,
    pub recipe_id: u64,
    pub ingredient_name: String,
    pub quantity: f64,
    pub unit: String,
    pub is_optional: bool,
    pub substitute: String,
}


impl __sdk::InModule for RecipeIngredient {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `RecipeIngredient`.
///
/// Provides typed access to columns for query building.
pub struct RecipeIngredientCols {
    pub recipe_ingredient_id: __sdk::__query_builder::Col<RecipeIngredient, u64>,
    pub recipe_id: __sdk::__query_builder::Col<RecipeIngredient, u64>,
    pub ingredient_name: __sdk::__query_builder::Col<RecipeIngredient, String>,
    pub quantity: __sdk::__query_builder::Col<RecipeIngredient, f64>,
    pub unit: __sdk::__query_builder::Col<RecipeIngredient, String>,
    pub is_optional: __sdk::__query_builder::Col<RecipeIngredient, bool>,
    pub substitute: __sdk::__query_builder::Col<RecipeIngredient, String>,
}

impl __sdk::__query_builder::HasCols for RecipeIngredient {
    type Cols = RecipeIngredientCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RecipeIngredientCols {
            recipe_ingredient_id: __sdk::__query_builder::Col::new(table_name, "recipe_ingredient_id"),
            recipe_id: __sdk::__query_builder::Col::new(table_name, "recipe_id"),
            ingredient_name: __sdk::__query_builder::Col::new(table_name, "ingredient_name"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            unit: __sdk::__query_builder::Col::new(table_name, "unit"),
            is_optional: __sdk::__query_builder::Col::new(table_name, "is_optional"),
            substitute: __sdk::__query_builder::Col::new(table_name, "substitute"),

        }
    }
}

/// Indexed column accessor struct for the table `RecipeIngredient`.
///
/// Provides typed access to indexed columns for query building.
pub struct RecipeIngredientIxCols {
    pub recipe_id: __sdk::__query_builder::IxCol<RecipeIngredient, u64>,
    pub recipe_ingredient_id: __sdk::__query_builder::IxCol<RecipeIngredient, u64>,
}

impl __sdk::__query_builder::HasIxCols for RecipeIngredient {
    type IxCols = RecipeIngredientIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RecipeIngredientIxCols {
            recipe_id: __sdk::__query_builder::IxCol::new(table_name, "recipe_id"),
            recipe_ingredient_id: __sdk::__query_builder::IxCol::new(table_name, "recipe_ingredient_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RecipeIngredient {}

