// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::recipe_type::Recipe;

/// Table handle for the table `recipe`.
///
/// Obtain a handle from the [`RecipeTableAccess::recipe`] method on [`super::RemoteTables`],
/// like `ctx.db.recipe()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.recipe().on_insert(...)`.
pub struct RecipeTableHandle<'ctx> {
    imp: __sdk::TableHandle<Recipe>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `recipe`.
pub struct RecipeTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RecipeTableAccessor {
    type Row = Recipe;
    type Handle<'db> = RecipeTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.recipe()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `recipe`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RecipeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RecipeTableHandle`], which mediates access to the table `recipe`.
    fn recipe(&self) -> RecipeTableHandle<'_>;
}

impl RecipeTableAccess for super::RemoteTables {
    fn recipe(&self) -> RecipeTableHandle<'_> {
        RecipeTableHandle {
            imp: self.imp.get_table::<Recipe>("recipe"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RecipeInsertCallbackId(__sdk::CallbackId);
pub struct RecipeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RecipeTableHandle<'ctx> {
    type Row = Recipe;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Recipe> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for RecipeTableHandle<'ctx> {
    type Row = Recipe;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Recipe> + '_ { self.imp.iter() }

    type InsertCallbackId = RecipeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeInsertCallbackId {
        RecipeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RecipeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RecipeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeDeleteCallbackId {
        RecipeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RecipeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RecipeTableHandle<'ctx> {
    type InsertCallbackId = RecipeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeInsertCallbackId {
        RecipeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RecipeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RecipeTableHandle<'ctx> {
    type DeleteCallbackId = RecipeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeDeleteCallbackId {
        RecipeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RecipeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RecipeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RecipeTableHandle<'ctx> {
    type UpdateCallbackId = RecipeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RecipeUpdateCallbackId {
        RecipeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RecipeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RecipeTableHandle<'ctx> {
    type UpdateCallbackId = RecipeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RecipeUpdateCallbackId {
        RecipeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RecipeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `recipe_id` unique index on the table `recipe`,
        /// which allows point queries on the field of the same name
        /// via the [`RecipeRecipeIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.recipe().recipe_id().find(...)`.
        pub struct RecipeRecipeIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Recipe, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> RecipeTableHandle<'ctx> {
            /// Get a handle on the `recipe_id` unique index on the table `recipe`.
            pub fn recipe_id(&self) -> RecipeRecipeIdUnique<'ctx> {
                RecipeRecipeIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("recipe_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> RecipeRecipeIdUnique<'ctx> {
            /// Find the subscribed row whose `recipe_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<Recipe> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Recipe>("recipe");
    _table.add_unique_constraint::<u64>("recipe_id", |row| &row.recipe_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Recipe>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Recipe>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Recipe`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait recipeQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Recipe`.
            fn recipe(&self) -> __sdk::__query_builder::Table<Recipe>;
        }

        impl recipeQueryTableAccess for __sdk::QueryTableAccessor {
            fn recipe(&self) -> __sdk::__query_builder::Table<Recipe> {
                __sdk::__query_builder::Table::new("recipe")
            }
        }

