// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::shopping_list_item_type::ShoppingListItem;

/// Table handle for the table `shopping_list_item`.
///
/// Obtain a handle from the [`ShoppingListItemTableAccess::shopping_list_item`] method on [`super::RemoteTables`],
/// like `ctx.db.shopping_list_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.shopping_list_item().on_insert(...)`.
pub struct ShoppingListItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShoppingListItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `shopping_list_item`.
pub struct ShoppingListItemTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ShoppingListItemTableAccessor {
    type Row = ShoppingListItem;
    type Handle<'db> = ShoppingListItemTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.shopping_list_item()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `shopping_list_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShoppingListItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShoppingListItemTableHandle`], which mediates access to the table `shopping_list_item`.
    fn shopping_list_item(&self) -> ShoppingListItemTableHandle<'_>;
}

impl ShoppingListItemTableAccess for super::RemoteTables {
    fn shopping_list_item(&self) -> ShoppingListItemTableHandle<'_> {
        ShoppingListItemTableHandle {
            imp: self.imp.get_table::<ShoppingListItem>("shopping_list_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShoppingListItemInsertCallbackId(__sdk::CallbackId);
pub struct ShoppingListItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ShoppingListItemTableHandle<'ctx> {
    type Row = ShoppingListItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ShoppingListItem> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for ShoppingListItemTableHandle<'ctx> {
    type Row = ShoppingListItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ShoppingListItem> + '_ { self.imp.iter() }

    type InsertCallbackId = ShoppingListItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShoppingListItemInsertCallbackId {
        ShoppingListItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShoppingListItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShoppingListItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShoppingListItemDeleteCallbackId {
        ShoppingListItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShoppingListItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ShoppingListItemTableHandle<'ctx> {
    type InsertCallbackId = ShoppingListItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShoppingListItemInsertCallbackId {
        ShoppingListItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShoppingListItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ShoppingListItemTableHandle<'ctx> {
    type DeleteCallbackId = ShoppingListItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShoppingListItemDeleteCallbackId {
        ShoppingListItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShoppingListItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ShoppingListItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShoppingListItemTableHandle<'ctx> {
    type UpdateCallbackId = ShoppingListItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShoppingListItemUpdateCallbackId {
        ShoppingListItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShoppingListItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ShoppingListItemTableHandle<'ctx> {
    type UpdateCallbackId = ShoppingListItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShoppingListItemUpdateCallbackId {
        ShoppingListItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShoppingListItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `shopping_item_id` unique index on the table `shopping_list_item`,
        /// which allows point queries on the field of the same name
        /// via the [`ShoppingListItemShoppingItemIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.shopping_list_item().shopping_item_id().find(...)`.
        pub struct ShoppingListItemShoppingItemIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ShoppingListItem, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ShoppingListItemTableHandle<'ctx> {
            /// Get a handle on the `shopping_item_id` unique index on the table `shopping_list_item`.
            pub fn shopping_item_id(&self) -> ShoppingListItemShoppingItemIdUnique<'ctx> {
                ShoppingListItemShoppingItemIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("shopping_item_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ShoppingListItemShoppingItemIdUnique<'ctx> {
            /// Find the subscribed row whose `shopping_item_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<ShoppingListItem> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ShoppingListItem>("shopping_list_item");
    _table.add_unique_constraint::<u64>("shopping_item_id", |row| &row.shopping_item_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ShoppingListItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ShoppingListItem>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ShoppingListItem`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait shopping_list_itemQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ShoppingListItem`.
            fn shopping_list_item(&self) -> __sdk::__query_builder::Table<ShoppingListItem>;
        }

        impl shopping_list_itemQueryTableAccess for __sdk::QueryTableAccessor {
            fn shopping_list_item(&self) -> __sdk::__query_builder::Table<ShoppingListItem> {
                __sdk::__query_builder::Table::new("shopping_list_item")
            }
        }

