// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShoppingListItem {
    pub shopping_item_id: u64,
    pub name: String,
    pub quantity: f64,
    pub unit: String,
    pub is_staple: bool,
    pub reason: String,
    pub added_by: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}


impl __sdk::InModule for ShoppingListItem {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ShoppingListItem`.
///
/// Provides typed access to columns for query building.
pub struct ShoppingListItemCols {
    pub shopping_item_id: __sdk::__query_builder::Col<ShoppingListItem, u64>,
    pub name: __sdk::__query_builder::Col<ShoppingListItem, String>,
    pub quantity: __sdk::__query_builder::Col<ShoppingListItem, f64>,
    pub unit: __sdk::__query_builder::Col<ShoppingListItem, String>,
    pub is_staple: __sdk::__query_builder::Col<ShoppingListItem, bool>,
    pub reason: __sdk::__query_builder::Col<ShoppingListItem, String>,
    pub added_by: __sdk::__query_builder::Col<ShoppingListItem, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<ShoppingListItem, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ShoppingListItem {
    type Cols = ShoppingListItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShoppingListItemCols {
            shopping_item_id: __sdk::__query_builder::Col::new(table_name, "shopping_item_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            unit: __sdk::__query_builder::Col::new(table_name, "unit"),
            is_staple: __sdk::__query_builder::Col::new(table_name, "is_staple"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            added_by: __sdk::__query_builder::Col::new(table_name, "added_by"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),

        }
    }
}

/// Indexed column accessor struct for the table `ShoppingListItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShoppingListItemIxCols {
    pub name: __sdk::__query_builder::IxCol<ShoppingListItem, String>,
    pub shopping_item_id: __sdk::__query_builder::IxCol<ShoppingListItem, u64>,
}

impl __sdk::__query_builder::HasIxCols for ShoppingListItem {
    type IxCols = ShoppingListItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShoppingListItemIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
            shopping_item_id: __sdk::__query_builder::IxCol::new(table_name, "shopping_item_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ShoppingListItem {}

