// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptRecipeReducer from "../accept_recipe_reducer";
import AddItemReducer from "../add_item_reducer";
import AddReceiptReducer from "../add_receipt_reducer";
import AddReceiptItemReducer from "../add_receipt_item_reducer";
import AddRecipeReducer from "../add_recipe_reducer";
import AddRecipeIngredientReducer from "../add_recipe_ingredient_reducer";
import AddShoppingItemReducer from "../add_shopping_item_reducer";
import AgentHeartbeatReducer from "../agent_heartbeat_reducer";
import DepleteItemReducer from "../deplete_item_reducer";
import MarkIngestFailedReducer from "../mark_ingest_failed_reducer";
import MarkIngestProcessedReducer from "../mark_ingest_processed_reducer";
import MarkOutboxDeliveredReducer from "../mark_outbox_delivered_reducer";
import MatchReceiptItemReducer from "../match_receipt_item_reducer";
import RemoveItemReducer from "../remove_item_reducer";
import RemoveShoppingItemReducer from "../remove_shopping_item_reducer";
import SetUserNameReducer from "../set_user_name_reducer";
import SubmitIngestReducer from "../submit_ingest_reducer";
import SubscribeDigestReducer from "../subscribe_digest_reducer";
import UnsubscribeDigestReducer from "../unsubscribe_digest_reducer";
import UpdateItemLocationReducer from "../update_item_location_reducer";
import UpdateItemQuantityReducer from "../update_item_quantity_reducer";

export type AcceptRecipeParams = __Infer<typeof AcceptRecipeReducer>;
export type AddItemParams = __Infer<typeof AddItemReducer>;
export type AddReceiptParams = __Infer<typeof AddReceiptReducer>;
export type AddReceiptItemParams = __Infer<typeof AddReceiptItemReducer>;
export type AddRecipeParams = __Infer<typeof AddRecipeReducer>;
export type AddRecipeIngredientParams = __Infer<typeof AddRecipeIngredientReducer>;
export type AddShoppingItemParams = __Infer<typeof AddShoppingItemReducer>;
export type AgentHeartbeatParams = __Infer<typeof AgentHeartbeatReducer>;
export type DepleteItemParams = __Infer<typeof DepleteItemReducer>;
export type MarkIngestFailedParams = __Infer<typeof MarkIngestFailedReducer>;
export type MarkIngestProcessedParams = __Infer<typeof MarkIngestProcessedReducer>;
export type MarkOutboxDeliveredParams = __Infer<typeof MarkOutboxDeliveredReducer>;
export type MatchReceiptItemParams = __Infer<typeof MatchReceiptItemReducer>;
export type RemoveItemParams = __Infer<typeof RemoveItemReducer>;
export type RemoveShoppingItemParams = __Infer<typeof RemoveShoppingItemReducer>;
export type SetUserNameParams = __Infer<typeof SetUserNameReducer>;
export type SubmitIngestParams = __Infer<typeof SubmitIngestReducer>;
export type SubscribeDigestParams = __Infer<typeof SubscribeDigestReducer>;
export type UnsubscribeDigestParams = __Infer<typeof UnsubscribeDigestReducer>;
export type UpdateItemLocationParams = __Infer<typeof UpdateItemLocationReducer>;
export type UpdateItemQuantityParams = __Infer<typeof UpdateItemQuantityReducer>;

