// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddShoppingItemArgs {
    pub name: String,
    pub quantity: f64,
    pub unit: String,
    pub is_staple: bool,
    pub reason: String,
}

impl From<AddShoppingItemArgs> for super::Reducer {
    fn from(args: AddShoppingItemArgs) -> Self {
        Self::AddShoppingItem {
            name: args.name,
            quantity: args.quantity,
            unit: args.unit,
            is_staple: args.is_staple,
            reason: args.reason,
}
}
}

impl __sdk::InModule for AddShoppingItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_shopping_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_shopping_item {
    /// Request that the remote module invoke the reducer `add_shopping_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_shopping_item:add_shopping_item_then`] to run a callback after the reducer completes.
    fn add_shopping_item(&self, name: String,
quantity: f64,
unit: String,
is_staple: bool,
reason: String,
) -> __sdk::Result<()> {
        self.add_shopping_item_then(name, quantity, unit, is_staple, reason,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_shopping_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_shopping_item_then(
        &self,
        name: String,
quantity: f64,
unit: String,
is_staple: bool,
reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_shopping_item for super::RemoteReducers {
    fn add_shopping_item_then(
        &self,
        name: String,
quantity: f64,
unit: String,
is_staple: bool,
reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AddShoppingItemArgs { name, quantity, unit, is_staple, reason,  }, callback)
    }
}

