// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddReceiptItemArgs {
    pub receipt_id: u64,
    pub product_name: String,
    pub quantity: f64,
    pub unit: String,
    pub price: f64,
    pub currency: String,
}

impl From<AddReceiptItemArgs> for super::Reducer {
    fn from(args: AddReceiptItemArgs) -> Self {
        Self::AddReceiptItem {
            receipt_id: args.receipt_id,
            product_name: args.product_name,
            quantity: args.quantity,
            unit: args.unit,
            price: args.price,
            currency: args.currency,
}
}
}

impl __sdk::InModule for AddReceiptItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_receipt_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_receipt_item {
    /// Request that the remote module invoke the reducer `add_receipt_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_receipt_item:add_receipt_item_then`] to run a callback after the reducer completes.
    fn add_receipt_item(&self, receipt_id: u64,
product_name: String,
quantity: f64,
unit: String,
price: f64,
currency: String,
) -> __sdk::Result<()> {
        self.add_receipt_item_then(receipt_id, product_name, quantity, unit, price, currency,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_receipt_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_receipt_item_then(
        &self,
        receipt_id: u64,
product_name: String,
quantity: f64,
unit: String,
price: f64,
currency: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_receipt_item for super::RemoteReducers {
    fn add_receipt_item_then(
        &self,
        receipt_id: u64,
product_name: String,
quantity: f64,
unit: String,
price: f64,
currency: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AddReceiptItemArgs { receipt_id, product_name, quantity, unit, price, currency,  }, callback)
    }
}

