// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddRecipeIngredientArgs {
    pub recipe_id: u64,
    pub ingredient_name: String,
    pub quantity: f64,
    pub unit: String,
    pub is_optional: bool,
    pub substitute: String,
}

impl From<AddRecipeIngredientArgs> for super::Reducer {
    fn from(args: AddRecipeIngredientArgs) -> Self {
        Self::AddRecipeIngredient {
            recipe_id: args.recipe_id,
            ingredient_name: args.ingredient_name,
            quantity: args.quantity,
            unit: args.unit,
            is_optional: args.is_optional,
            substitute: args.substitute,
}
}
}

impl __sdk::InModule for AddRecipeIngredientArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_recipe_ingredient`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_recipe_ingredient {
    /// Request that the remote module invoke the reducer `add_recipe_ingredient` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_recipe_ingredient:add_recipe_ingredient_then`] to run a callback after the reducer completes.
    fn add_recipe_ingredient(&self, recipe_id: u64,
ingredient_name: String,
quantity: f64,
unit: String,
is_optional: bool,
substitute: String,
) -> __sdk::Result<()> {
        self.add_recipe_ingredient_then(recipe_id, ingredient_name, quantity, unit, is_optional, substitute,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_recipe_ingredient` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_recipe_ingredient_then(
        &self,
        recipe_id: u64,
ingredient_name: String,
quantity: f64,
unit: String,
is_optional: bool,
substitute: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_recipe_ingredient for super::RemoteReducers {
    fn add_recipe_ingredient_then(
        &self,
        recipe_id: u64,
ingredient_name: String,
quantity: f64,
unit: String,
is_optional: bool,
substitute: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AddRecipeIngredientArgs { recipe_id, ingredient_name, quantity, unit, is_optional, substitute,  }, callback)
    }
}

