// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DepleteItemArgs {
    pub item_id: u64,
}

impl From<DepleteItemArgs> for super::Reducer {
    fn from(args: DepleteItemArgs) -> Self {
        Self::DepleteItem {
            item_id: args.item_id,
}
}
}

impl __sdk::InModule for DepleteItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `deplete_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait deplete_item {
    /// Request that the remote module invoke the reducer `deplete_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`deplete_item:deplete_item_then`] to run a callback after the reducer completes.
    fn deplete_item(&self, item_id: u64,
) -> __sdk::Result<()> {
        self.deplete_item_then(item_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `deplete_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn deplete_item_then(
        &self,
        item_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl deplete_item for super::RemoteReducers {
    fn deplete_item_then(
        &self,
        item_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(DepleteItemArgs { item_id,  }, callback)
    }
}

