// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DigestOutbox {
    pub outbox_id: u64,
    pub subscription_id: u64,
    pub channel: String,
    pub handle: String,
    pub message: String,
    pub item_count: u32,
    pub is_delivered: bool,
    pub created_at: __sdk::Timestamp,
}


impl __sdk::InModule for DigestOutbox {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `DigestOutbox`.
///
/// Provides typed access to columns for query building.
pub struct DigestOutboxCols {
    pub outbox_id: __sdk::__query_builder::Col<DigestOutbox, u64>,
    pub subscription_id: __sdk::__query_builder::Col<DigestOutbox, u64>,
    pub channel: __sdk::__query_builder::Col<DigestOutbox, String>,
    pub handle: __sdk::__query_builder::Col<DigestOutbox, String>,
    pub message: __sdk::__query_builder::Col<DigestOutbox, String>,
    pub item_count: __sdk::__query_builder::Col<DigestOutbox, u32>,
    pub is_delivered: __sdk::__query_builder::Col<DigestOutbox, bool>,
    pub created_at: __sdk::__query_builder::Col<DigestOutbox, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for DigestOutbox {
    type Cols = DigestOutboxCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DigestOutboxCols {
            outbox_id: __sdk::__query_builder::Col::new(table_name, "outbox_id"),
            subscription_id: __sdk::__query_builder::Col::new(table_name, "subscription_id"),
            channel: __sdk::__query_builder::Col::new(table_name, "channel"),
            handle: __sdk::__query_builder::Col::new(table_name, "handle"),
            message: __sdk::__query_builder::Col::new(table_name, "message"),
            item_count: __sdk::__query_builder::Col::new(table_name, "item_count"),
            is_delivered: __sdk::__query_builder::Col::new(table_name, "is_delivered"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),

        }
    }
}

/// Indexed column accessor struct for the table `DigestOutbox`.
///
/// Provides typed access to indexed columns for query building.
pub struct DigestOutboxIxCols {
    pub outbox_id: __sdk::__query_builder::IxCol<DigestOutbox, u64>,
    pub subscription_id: __sdk::__query_builder::IxCol<DigestOutbox, u64>,
}

impl __sdk::__query_builder::HasIxCols for DigestOutbox {
    type IxCols = DigestOutboxIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DigestOutboxIxCols {
            outbox_id: __sdk::__query_builder::IxCol::new(table_name, "outbox_id"),
            subscription_id: __sdk::__query_builder::IxCol::new(table_name, "subscription_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DigestOutbox {}

