// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::location_type::Location;
use super::item_status_type::ItemStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Item {
    pub item_id: u64,
    pub name: String,
    pub display_name: String,
    pub barcode: String,
    pub quantity: f64,
    pub unit: String,
    pub location: Location,
    pub status: ItemStatus,
    pub est_expiry_ts: i64,
    pub unopened_days: i32,
    pub opened_days: i32,
    pub price: f64,
    pub currency: String,
    pub source_receipt_id: u64,
    pub added_by: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}


impl __sdk::InModule for Item {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Item`.
///
/// Provides typed access to columns for query building.
pub struct ItemCols {
    pub item_id: __sdk::__query_builder::Col<Item, u64>,
    pub name: __sdk::__query_builder::Col<Item, String>,
    pub display_name: __sdk::__query_builder::Col<Item, String>,
    pub barcode: __sdk::__query_builder::Col<Item, String>,
    pub quantity: __sdk::__query_builder::Col<Item, f64>,
    pub unit: __sdk::__query_builder::Col<Item, String>,
    pub location: __sdk::__query_builder::Col<Item, Location>,
    pub status: __sdk::__query_builder::Col<Item, ItemStatus>,
    pub est_expiry_ts: __sdk::__query_builder::Col<Item, i64>,
    pub unopened_days: __sdk::__query_builder::Col<Item, i32>,
    pub opened_days: __sdk::__query_builder::Col<Item, i32>,
    pub price: __sdk::__query_builder::Col<Item, f64>,
    pub currency: __sdk::__query_builder::Col<Item, String>,
    pub source_receipt_id: __sdk::__query_builder::Col<Item, u64>,
    pub added_by: __sdk::__query_builder::Col<Item, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<Item, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Item, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Item {
    type Cols = ItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ItemCols {
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            barcode: __sdk::__query_builder::Col::new(table_name, "barcode"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            unit: __sdk::__query_builder::Col::new(table_name, "unit"),
            location: __sdk::__query_builder::Col::new(table_name, "location"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            est_expiry_ts: __sdk::__query_builder::Col::new(table_name, "est_expiry_ts"),
            unopened_days: __sdk::__query_builder::Col::new(table_name, "unopened_days"),
            opened_days: __sdk::__query_builder::Col::new(table_name, "opened_days"),
            price: __sdk::__query_builder::Col::new(table_name, "price"),
            currency: __sdk::__query_builder::Col::new(table_name, "currency"),
            source_receipt_id: __sdk::__query_builder::Col::new(table_name, "source_receipt_id"),
            added_by: __sdk::__query_builder::Col::new(table_name, "added_by"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),

        }
    }
}

/// Indexed column accessor struct for the table `Item`.
///
/// Provides typed access to indexed columns for query building.
pub struct ItemIxCols {
    pub barcode: __sdk::__query_builder::IxCol<Item, String>,
    pub est_expiry_ts: __sdk::__query_builder::IxCol<Item, i64>,
    pub item_id: __sdk::__query_builder::IxCol<Item, u64>,
    pub location: __sdk::__query_builder::IxCol<Item, Location>,
    pub name: __sdk::__query_builder::IxCol<Item, String>,
}

impl __sdk::__query_builder::HasIxCols for Item {
    type IxCols = ItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ItemIxCols {
            barcode: __sdk::__query_builder::IxCol::new(table_name, "barcode"),
            est_expiry_ts: __sdk::__query_builder::IxCol::new(table_name, "est_expiry_ts"),
            item_id: __sdk::__query_builder::IxCol::new(table_name, "item_id"),
            location: __sdk::__query_builder::IxCol::new(table_name, "location"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Item {}

