// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.2 (commit 524b4487d949b61a07d4f39c862d1290259dfd20).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

pub mod digest_outbox_type;
pub mod digest_schedule_type;
pub mod digest_subscription_type;
pub mod expiry_sweep_schedule_type;
pub mod item_type;
pub mod item_status_type;
pub mod location_type;
pub mod pantry_event_type;
pub mod receipt_type;
pub mod receipt_item_type;
pub mod recipe_type;
pub mod recipe_ingredient_type;
pub mod shopping_list_item_type;
pub mod user_type;
pub mod accept_recipe_reducer;
pub mod add_item_reducer;
pub mod add_receipt_reducer;
pub mod add_receipt_item_reducer;
pub mod add_recipe_reducer;
pub mod add_recipe_ingredient_reducer;
pub mod add_shopping_item_reducer;
pub mod deplete_item_reducer;
pub mod mark_outbox_delivered_reducer;
pub mod match_receipt_item_reducer;
pub mod remove_item_reducer;
pub mod remove_shopping_item_reducer;
pub mod set_user_name_reducer;
pub mod subscribe_digest_reducer;
pub mod unsubscribe_digest_reducer;
pub mod update_item_location_reducer;
pub mod update_item_quantity_reducer;
pub mod digest_outbox_table;
pub mod digest_subscription_table;
pub mod item_table;
pub mod pantry_event_table;
pub mod receipt_table;
pub mod receipt_item_table;
pub mod recipe_table;
pub mod recipe_ingredient_table;
pub mod shopping_list_item_table;
pub mod user_table;

pub use digest_outbox_type::DigestOutbox;
pub use digest_schedule_type::DigestSchedule;
pub use digest_subscription_type::DigestSubscription;
pub use expiry_sweep_schedule_type::ExpirySweepSchedule;
pub use item_type::Item;
pub use item_status_type::ItemStatus;
pub use location_type::Location;
pub use pantry_event_type::PantryEvent;
pub use receipt_type::Receipt;
pub use receipt_item_type::ReceiptItem;
pub use recipe_type::Recipe;
pub use recipe_ingredient_type::RecipeIngredient;
pub use shopping_list_item_type::ShoppingListItem;
pub use user_type::User;
pub use digest_outbox_table::*;
pub use digest_subscription_table::*;
pub use item_table::*;
pub use pantry_event_table::*;
pub use receipt_table::*;
pub use receipt_item_table::*;
pub use recipe_table::*;
pub use recipe_ingredient_table::*;
pub use shopping_list_item_table::*;
pub use user_table::*;
pub use accept_recipe_reducer::accept_recipe;
pub use add_item_reducer::add_item;
pub use add_receipt_reducer::add_receipt;
pub use add_receipt_item_reducer::add_receipt_item;
pub use add_recipe_reducer::add_recipe;
pub use add_recipe_ingredient_reducer::add_recipe_ingredient;
pub use add_shopping_item_reducer::add_shopping_item;
pub use deplete_item_reducer::deplete_item;
pub use mark_outbox_delivered_reducer::mark_outbox_delivered;
pub use match_receipt_item_reducer::match_receipt_item;
pub use remove_item_reducer::remove_item;
pub use remove_shopping_item_reducer::remove_shopping_item;
pub use set_user_name_reducer::set_user_name;
pub use subscribe_digest_reducer::subscribe_digest;
pub use unsubscribe_digest_reducer::unsubscribe_digest;
pub use update_item_location_reducer::update_item_location;
pub use update_item_quantity_reducer::update_item_quantity;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
        AcceptRecipe {
        recipe_id: u64,
}    ,
    AddItem {
        name: String,
        display_name: String,
        quantity: f64,
        unit: String,
        location: Location,
        est_expiry_ts: i64,
        unopened_days: i32,
        opened_days: i32,
        price: f64,
        currency: String,
        barcode: String,
        source_receipt_id: u64,
}    ,
    AddReceipt {
        store_name: String,
        purchased_at: i64,
        total: f64,
        tax: f64,
        currency: String,
        raw_ocr_text: String,
        image_url: String,
}    ,
    AddReceiptItem {
        receipt_id: u64,
        product_name: String,
        quantity: f64,
        unit: String,
        price: f64,
        currency: String,
}    ,
    AddRecipe {
        name: String,
        servings: u8,
        instructions: String,
        source_url: String,
}    ,
    AddRecipeIngredient {
        recipe_id: u64,
        ingredient_name: String,
        quantity: f64,
        unit: String,
        is_optional: bool,
        substitute: String,
}    ,
    AddShoppingItem {
        name: String,
        quantity: f64,
        unit: String,
        is_staple: bool,
        reason: String,
}    ,
    DepleteItem {
        item_id: u64,
}    ,
    MarkOutboxDelivered {
        outbox_id: u64,
}    ,
    MatchReceiptItem {
        receipt_item_id: u64,
        item_id: u64,
}    ,
    RemoveItem {
        item_id: u64,
}    ,
    RemoveShoppingItem {
        shopping_item_id: u64,
}    ,
    SetUserName {
        name: String,
}    ,
    SubscribeDigest {
        channel: String,
        handle: String,
}    ,
    UnsubscribeDigest {
        subscription_id: u64,
}    ,
    UpdateItemLocation {
        item_id: u64,
        location: Location,
}    ,
    UpdateItemQuantity {
        item_id: u64,
        new_quantity: f64,
}    ,
}


impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
                        Reducer::AcceptRecipe { .. } => "accept_recipe",
            Reducer::AddItem { .. } => "add_item",
            Reducer::AddReceipt { .. } => "add_receipt",
            Reducer::AddReceiptItem { .. } => "add_receipt_item",
            Reducer::AddRecipe { .. } => "add_recipe",
            Reducer::AddRecipeIngredient { .. } => "add_recipe_ingredient",
            Reducer::AddShoppingItem { .. } => "add_shopping_item",
            Reducer::DepleteItem { .. } => "deplete_item",
            Reducer::MarkOutboxDelivered { .. } => "mark_outbox_delivered",
            Reducer::MatchReceiptItem { .. } => "match_receipt_item",
            Reducer::RemoveItem { .. } => "remove_item",
            Reducer::RemoveShoppingItem { .. } => "remove_shopping_item",
            Reducer::SetUserName { .. } => "set_user_name",
            Reducer::SubscribeDigest { .. } => "subscribe_digest",
            Reducer::UnsubscribeDigest { .. } => "unsubscribe_digest",
            Reducer::UpdateItemLocation { .. } => "update_item_location",
            Reducer::UpdateItemQuantity { .. } => "update_item_quantity",
            _ => unreachable!(),
}
}
    #[allow(clippy::clone_on_copy)]
fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
                        Reducer::AcceptRecipe{
                recipe_id,
}             => __sats::bsatn::to_vec(&accept_recipe_reducer::AcceptRecipeArgs {
                recipe_id: recipe_id.clone(),
}),
            Reducer::AddItem{
                name,
                display_name,
                quantity,
                unit,
                location,
                est_expiry_ts,
                unopened_days,
                opened_days,
                price,
                currency,
                barcode,
                source_receipt_id,
}             => __sats::bsatn::to_vec(&add_item_reducer::AddItemArgs {
                name: name.clone(),
                display_name: display_name.clone(),
                quantity: quantity.clone(),
                unit: unit.clone(),
                location: location.clone(),
                est_expiry_ts: est_expiry_ts.clone(),
                unopened_days: unopened_days.clone(),
                opened_days: opened_days.clone(),
                price: price.clone(),
                currency: currency.clone(),
                barcode: barcode.clone(),
                source_receipt_id: source_receipt_id.clone(),
}),
            Reducer::AddReceipt{
                store_name,
                purchased_at,
                total,
                tax,
                currency,
                raw_ocr_text,
                image_url,
}             => __sats::bsatn::to_vec(&add_receipt_reducer::AddReceiptArgs {
                store_name: store_name.clone(),
                purchased_at: purchased_at.clone(),
                total: total.clone(),
                tax: tax.clone(),
                currency: currency.clone(),
                raw_ocr_text: raw_ocr_text.clone(),
                image_url: image_url.clone(),
}),
            Reducer::AddReceiptItem{
                receipt_id,
                product_name,
                quantity,
                unit,
                price,
                currency,
}             => __sats::bsatn::to_vec(&add_receipt_item_reducer::AddReceiptItemArgs {
                receipt_id: receipt_id.clone(),
                product_name: product_name.clone(),
                quantity: quantity.clone(),
                unit: unit.clone(),
                price: price.clone(),
                currency: currency.clone(),
}),
            Reducer::AddRecipe{
                name,
                servings,
                instructions,
                source_url,
}             => __sats::bsatn::to_vec(&add_recipe_reducer::AddRecipeArgs {
                name: name.clone(),
                servings: servings.clone(),
                instructions: instructions.clone(),
                source_url: source_url.clone(),
}),
            Reducer::AddRecipeIngredient{
                recipe_id,
                ingredient_name,
                quantity,
                unit,
                is_optional,
                substitute,
}             => __sats::bsatn::to_vec(&add_recipe_ingredient_reducer::AddRecipeIngredientArgs {
                recipe_id: recipe_id.clone(),
                ingredient_name: ingredient_name.clone(),
                quantity: quantity.clone(),
                unit: unit.clone(),
                is_optional: is_optional.clone(),
                substitute: substitute.clone(),
}),
            Reducer::AddShoppingItem{
                name,
                quantity,
                unit,
                is_staple,
                reason,
}             => __sats::bsatn::to_vec(&add_shopping_item_reducer::AddShoppingItemArgs {
                name: name.clone(),
                quantity: quantity.clone(),
                unit: unit.clone(),
                is_staple: is_staple.clone(),
                reason: reason.clone(),
}),
            Reducer::DepleteItem{
                item_id,
}             => __sats::bsatn::to_vec(&deplete_item_reducer::DepleteItemArgs {
                item_id: item_id.clone(),
}),
            Reducer::MarkOutboxDelivered{
                outbox_id,
}             => __sats::bsatn::to_vec(&mark_outbox_delivered_reducer::MarkOutboxDeliveredArgs {
                outbox_id: outbox_id.clone(),
}),
            Reducer::MatchReceiptItem{
                receipt_item_id,
                item_id,
}             => __sats::bsatn::to_vec(&match_receipt_item_reducer::MatchReceiptItemArgs {
                receipt_item_id: receipt_item_id.clone(),
                item_id: item_id.clone(),
}),
            Reducer::RemoveItem{
                item_id,
}             => __sats::bsatn::to_vec(&remove_item_reducer::RemoveItemArgs {
                item_id: item_id.clone(),
}),
            Reducer::RemoveShoppingItem{
                shopping_item_id,
}             => __sats::bsatn::to_vec(&remove_shopping_item_reducer::RemoveShoppingItemArgs {
                shopping_item_id: shopping_item_id.clone(),
}),
            Reducer::SetUserName{
                name,
}             => __sats::bsatn::to_vec(&set_user_name_reducer::SetUserNameArgs {
                name: name.clone(),
}),
            Reducer::SubscribeDigest{
                channel,
                handle,
}             => __sats::bsatn::to_vec(&subscribe_digest_reducer::SubscribeDigestArgs {
                channel: channel.clone(),
                handle: handle.clone(),
}),
            Reducer::UnsubscribeDigest{
                subscription_id,
}             => __sats::bsatn::to_vec(&unsubscribe_digest_reducer::UnsubscribeDigestArgs {
                subscription_id: subscription_id.clone(),
}),
            Reducer::UpdateItemLocation{
                item_id,
                location,
}             => __sats::bsatn::to_vec(&update_item_location_reducer::UpdateItemLocationArgs {
                item_id: item_id.clone(),
                location: location.clone(),
}),
            Reducer::UpdateItemQuantity{
                item_id,
                new_quantity,
}             => __sats::bsatn::to_vec(&update_item_quantity_reducer::UpdateItemQuantityArgs {
                item_id: item_id.clone(),
                new_quantity: new_quantity.clone(),
}),
            _ => unreachable!(),
}
}
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
        digest_outbox: __sdk::TableUpdate<DigestOutbox>,
    digest_subscription: __sdk::TableUpdate<DigestSubscription>,
    item: __sdk::TableUpdate<Item>,
    pantry_event: __sdk::TableUpdate<PantryEvent>,
    receipt: __sdk::TableUpdate<Receipt>,
    receipt_item: __sdk::TableUpdate<ReceiptItem>,
    recipe: __sdk::TableUpdate<Recipe>,
    recipe_ingredient: __sdk::TableUpdate<RecipeIngredient>,
    shopping_list_item: __sdk::TableUpdate<ShoppingListItem>,
    user: __sdk::TableUpdate<User>,
}


impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {

        "digest_outbox" => db_update.digest_outbox.append(digest_outbox_table::parse_table_update(table_update)?),
    "digest_subscription" => db_update.digest_subscription.append(digest_subscription_table::parse_table_update(table_update)?),
    "item" => db_update.item.append(item_table::parse_table_update(table_update)?),
    "pantry_event" => db_update.pantry_event.append(pantry_event_table::parse_table_update(table_update)?),
    "receipt" => db_update.receipt.append(receipt_table::parse_table_update(table_update)?),
    "receipt_item" => db_update.receipt_item.append(receipt_item_table::parse_table_update(table_update)?),
    "recipe" => db_update.recipe.append(recipe_table::parse_table_update(table_update)?),
    "recipe_ingredient" => db_update.recipe_ingredient.append(recipe_ingredient_table::parse_table_update(table_update)?),
    "shopping_list_item" => db_update.shopping_list_item.append(shopping_list_item_table::parse_table_update(table_update)?),
    "user" => db_update.user.append(user_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    ).into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(&self, cache: &mut __sdk::ClientCache<RemoteModule>) -> AppliedDiff<'_> {
                    let mut diff = AppliedDiff::default();
                
                diff.digest_outbox = cache.apply_diff_to_table::<DigestOutbox>("digest_outbox", &self.digest_outbox).with_updates_by_pk(|row| &row.outbox_id);
        diff.digest_subscription = cache.apply_diff_to_table::<DigestSubscription>("digest_subscription", &self.digest_subscription).with_updates_by_pk(|row| &row.subscription_id);
        diff.item = cache.apply_diff_to_table::<Item>("item", &self.item).with_updates_by_pk(|row| &row.item_id);
        diff.pantry_event = cache.apply_diff_to_table::<PantryEvent>("pantry_event", &self.pantry_event).with_updates_by_pk(|row| &row.event_id);
        diff.receipt = cache.apply_diff_to_table::<Receipt>("receipt", &self.receipt).with_updates_by_pk(|row| &row.receipt_id);
        diff.receipt_item = cache.apply_diff_to_table::<ReceiptItem>("receipt_item", &self.receipt_item).with_updates_by_pk(|row| &row.receipt_item_id);
        diff.recipe = cache.apply_diff_to_table::<Recipe>("recipe", &self.recipe).with_updates_by_pk(|row| &row.recipe_id);
        diff.recipe_ingredient = cache.apply_diff_to_table::<RecipeIngredient>("recipe_ingredient", &self.recipe_ingredient).with_updates_by_pk(|row| &row.recipe_ingredient_id);
        diff.shopping_list_item = cache.apply_diff_to_table::<ShoppingListItem>("shopping_list_item", &self.shopping_list_item).with_updates_by_pk(|row| &row.shopping_item_id);
        diff.user = cache.apply_diff_to_table::<User>("user", &self.user).with_updates_by_pk(|row| &row.identity);

                    diff
                }
fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "digest_outbox" => db_update.digest_outbox.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "digest_subscription" => db_update.digest_subscription.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "item" => db_update.item.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "pantry_event" => db_update.pantry_event.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "receipt" => db_update.receipt.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "receipt_item" => db_update.receipt_item.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "recipe" => db_update.recipe.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "recipe_ingredient" => db_update.recipe_ingredient.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "shopping_list_item" => db_update.shopping_list_item.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user" => db_update.user.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "digest_outbox" => db_update.digest_outbox.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "digest_subscription" => db_update.digest_subscription.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "item" => db_update.item.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "pantry_event" => db_update.pantry_event.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "receipt" => db_update.receipt.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "receipt_item" => db_update.receipt_item.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "recipe" => db_update.recipe.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "recipe_ingredient" => db_update.recipe_ingredient.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "shopping_list_item" => db_update.shopping_list_item.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user" => db_update.user.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
        digest_outbox: __sdk::TableAppliedDiff<'r, DigestOutbox>,
    digest_subscription: __sdk::TableAppliedDiff<'r, DigestSubscription>,
    item: __sdk::TableAppliedDiff<'r, Item>,
    pantry_event: __sdk::TableAppliedDiff<'r, PantryEvent>,
    receipt: __sdk::TableAppliedDiff<'r, Receipt>,
    receipt_item: __sdk::TableAppliedDiff<'r, ReceiptItem>,
    recipe: __sdk::TableAppliedDiff<'r, Recipe>,
    recipe_ingredient: __sdk::TableAppliedDiff<'r, RecipeIngredient>,
    shopping_list_item: __sdk::TableAppliedDiff<'r, ShoppingListItem>,
    user: __sdk::TableAppliedDiff<'r, User>,
    __unused: std::marker::PhantomData<&'r ()>,
}


impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(&self, event: &EventContext, callbacks: &mut __sdk::DbCallbacks<RemoteModule>) {
                callbacks.invoke_table_row_callbacks::<DigestOutbox>("digest_outbox", &self.digest_outbox, event);
        callbacks.invoke_table_row_callbacks::<DigestSubscription>("digest_subscription", &self.digest_subscription, event);
        callbacks.invoke_table_row_callbacks::<Item>("item", &self.item, event);
        callbacks.invoke_table_row_callbacks::<PantryEvent>("pantry_event", &self.pantry_event, event);
        callbacks.invoke_table_row_callbacks::<Receipt>("receipt", &self.receipt, event);
        callbacks.invoke_table_row_callbacks::<ReceiptItem>("receipt_item", &self.receipt_item, event);
        callbacks.invoke_table_row_callbacks::<Recipe>("recipe", &self.recipe, event);
        callbacks.invoke_table_row_callbacks::<RecipeIngredient>("recipe_ingredient", &self.recipe_ingredient, event);
        callbacks.invoke_table_row_callbacks::<ShoppingListItem>("shopping_list_item", &self.shopping_list_item, event);
        callbacks.invoke_table_row_callbacks::<User>("user", &self.user, event);
}
}


#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(target_arch = "wasm32", doc = "- [`DbConnection::run_background_task`].")]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(not(target_arch =  "wasm32"), doc = "- [`DbConnection::advance_one_message_blocking`].")]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }

}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
> {}
impl<Ctx: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>> RemoteDbContext for Ctx {}


/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
                digest_outbox_table::register_table(client_cache);
        digest_subscription_table::register_table(client_cache);
        item_table::register_table(client_cache);
        pantry_event_table::register_table(client_cache);
        receipt_table::register_table(client_cache);
        receipt_item_table::register_table(client_cache);
        recipe_table::register_table(client_cache);
        recipe_ingredient_table::register_table(client_cache);
        shopping_list_item_table::register_table(client_cache);
        user_table::register_table(client_cache);
}
const ALL_TABLE_NAMES: &'static [&'static str] = &[
                "digest_outbox",
        "digest_subscription",
        "item",
        "pantry_event",
        "receipt",
        "receipt_item",
        "recipe",
        "recipe_ingredient",
        "shopping_list_item",
        "user",
];
}
