// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PantryEvent {
    pub event_id: u64,
    pub event_type: String,
    pub item_id: u64,
    pub description: String,
    pub actor: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}


impl __sdk::InModule for PantryEvent {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `PantryEvent`.
///
/// Provides typed access to columns for query building.
pub struct PantryEventCols {
    pub event_id: __sdk::__query_builder::Col<PantryEvent, u64>,
    pub event_type: __sdk::__query_builder::Col<PantryEvent, String>,
    pub item_id: __sdk::__query_builder::Col<PantryEvent, u64>,
    pub description: __sdk::__query_builder::Col<PantryEvent, String>,
    pub actor: __sdk::__query_builder::Col<PantryEvent, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<PantryEvent, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PantryEvent {
    type Cols = PantryEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PantryEventCols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            event_type: __sdk::__query_builder::Col::new(table_name, "event_type"),
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),

        }
    }
}

/// Indexed column accessor struct for the table `PantryEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct PantryEventIxCols {
    pub event_id: __sdk::__query_builder::IxCol<PantryEvent, u64>,
    pub event_type: __sdk::__query_builder::IxCol<PantryEvent, String>,
}

impl __sdk::__query_builder::HasIxCols for PantryEvent {
    type IxCols = PantryEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PantryEventIxCols {
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
            event_type: __sdk::__query_builder::IxCol::new(table_name, "event_type"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PantryEvent {}

