// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::pantry_event_type::PantryEvent;

/// Table handle for the table `pantry_event`.
///
/// Obtain a handle from the [`PantryEventTableAccess::pantry_event`] method on [`super::RemoteTables`],
/// like `ctx.db.pantry_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pantry_event().on_insert(...)`.
pub struct PantryEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<PantryEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `pantry_event`.
pub struct PantryEventTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PantryEventTableAccessor {
    type Row = PantryEvent;
    type Handle<'db> = PantryEventTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.pantry_event()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pantry_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PantryEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PantryEventTableHandle`], which mediates access to the table `pantry_event`.
    fn pantry_event(&self) -> PantryEventTableHandle<'_>;
}

impl PantryEventTableAccess for super::RemoteTables {
    fn pantry_event(&self) -> PantryEventTableHandle<'_> {
        PantryEventTableHandle {
            imp: self.imp.get_table::<PantryEvent>("pantry_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PantryEventInsertCallbackId(__sdk::CallbackId);
pub struct PantryEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PantryEventTableHandle<'ctx> {
    type Row = PantryEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = PantryEvent> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for PantryEventTableHandle<'ctx> {
    type Row = PantryEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = PantryEvent> + '_ { self.imp.iter() }

    type InsertCallbackId = PantryEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PantryEventInsertCallbackId {
        PantryEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PantryEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PantryEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PantryEventDeleteCallbackId {
        PantryEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PantryEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PantryEventTableHandle<'ctx> {
    type InsertCallbackId = PantryEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PantryEventInsertCallbackId {
        PantryEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PantryEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PantryEventTableHandle<'ctx> {
    type DeleteCallbackId = PantryEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PantryEventDeleteCallbackId {
        PantryEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PantryEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PantryEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PantryEventTableHandle<'ctx> {
    type UpdateCallbackId = PantryEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PantryEventUpdateCallbackId {
        PantryEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PantryEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PantryEventTableHandle<'ctx> {
    type UpdateCallbackId = PantryEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PantryEventUpdateCallbackId {
        PantryEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PantryEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `event_id` unique index on the table `pantry_event`,
        /// which allows point queries on the field of the same name
        /// via the [`PantryEventEventIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.pantry_event().event_id().find(...)`.
        pub struct PantryEventEventIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<PantryEvent, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> PantryEventTableHandle<'ctx> {
            /// Get a handle on the `event_id` unique index on the table `pantry_event`.
            pub fn event_id(&self) -> PantryEventEventIdUnique<'ctx> {
                PantryEventEventIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("event_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> PantryEventEventIdUnique<'ctx> {
            /// Find the subscribed row whose `event_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<PantryEvent> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<PantryEvent>("pantry_event");
    _table.add_unique_constraint::<u64>("event_id", |row| &row.event_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PantryEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<PantryEvent>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `PantryEvent`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait pantry_eventQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `PantryEvent`.
            fn pantry_event(&self) -> __sdk::__query_builder::Table<PantryEvent>;
        }

        impl pantry_eventQueryTableAccess for __sdk::QueryTableAccessor {
            fn pantry_event(&self) -> __sdk::__query_builder::Table<PantryEvent> {
                __sdk::__query_builder::Table::new("pantry_event")
            }
        }

