// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::receipt_item_type::ReceiptItem;

/// Table handle for the table `receipt_item`.
///
/// Obtain a handle from the [`ReceiptItemTableAccess::receipt_item`] method on [`super::RemoteTables`],
/// like `ctx.db.receipt_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.receipt_item().on_insert(...)`.
pub struct ReceiptItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<ReceiptItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `receipt_item`.
pub struct ReceiptItemTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ReceiptItemTableAccessor {
    type Row = ReceiptItem;
    type Handle<'db> = ReceiptItemTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.receipt_item()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `receipt_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ReceiptItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ReceiptItemTableHandle`], which mediates access to the table `receipt_item`.
    fn receipt_item(&self) -> ReceiptItemTableHandle<'_>;
}

impl ReceiptItemTableAccess for super::RemoteTables {
    fn receipt_item(&self) -> ReceiptItemTableHandle<'_> {
        ReceiptItemTableHandle {
            imp: self.imp.get_table::<ReceiptItem>("receipt_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ReceiptItemInsertCallbackId(__sdk::CallbackId);
pub struct ReceiptItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ReceiptItemTableHandle<'ctx> {
    type Row = ReceiptItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ReceiptItem> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for ReceiptItemTableHandle<'ctx> {
    type Row = ReceiptItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ReceiptItem> + '_ { self.imp.iter() }

    type InsertCallbackId = ReceiptItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReceiptItemInsertCallbackId {
        ReceiptItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ReceiptItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ReceiptItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReceiptItemDeleteCallbackId {
        ReceiptItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ReceiptItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ReceiptItemTableHandle<'ctx> {
    type InsertCallbackId = ReceiptItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReceiptItemInsertCallbackId {
        ReceiptItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ReceiptItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ReceiptItemTableHandle<'ctx> {
    type DeleteCallbackId = ReceiptItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReceiptItemDeleteCallbackId {
        ReceiptItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ReceiptItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ReceiptItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ReceiptItemTableHandle<'ctx> {
    type UpdateCallbackId = ReceiptItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ReceiptItemUpdateCallbackId {
        ReceiptItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ReceiptItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ReceiptItemTableHandle<'ctx> {
    type UpdateCallbackId = ReceiptItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ReceiptItemUpdateCallbackId {
        ReceiptItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ReceiptItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `receipt_item_id` unique index on the table `receipt_item`,
        /// which allows point queries on the field of the same name
        /// via the [`ReceiptItemReceiptItemIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.receipt_item().receipt_item_id().find(...)`.
        pub struct ReceiptItemReceiptItemIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ReceiptItem, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ReceiptItemTableHandle<'ctx> {
            /// Get a handle on the `receipt_item_id` unique index on the table `receipt_item`.
            pub fn receipt_item_id(&self) -> ReceiptItemReceiptItemIdUnique<'ctx> {
                ReceiptItemReceiptItemIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("receipt_item_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ReceiptItemReceiptItemIdUnique<'ctx> {
            /// Find the subscribed row whose `receipt_item_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<ReceiptItem> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ReceiptItem>("receipt_item");
    _table.add_unique_constraint::<u64>("receipt_item_id", |row| &row.receipt_item_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ReceiptItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ReceiptItem>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ReceiptItem`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait receipt_itemQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ReceiptItem`.
            fn receipt_item(&self) -> __sdk::__query_builder::Table<ReceiptItem>;
        }

        impl receipt_itemQueryTableAccess for __sdk::QueryTableAccessor {
            fn receipt_item(&self) -> __sdk::__query_builder::Table<ReceiptItem> {
                __sdk::__query_builder::Table::new("receipt_item")
            }
        }

