// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::receipt_type::Receipt;

/// Table handle for the table `receipt`.
///
/// Obtain a handle from the [`ReceiptTableAccess::receipt`] method on [`super::RemoteTables`],
/// like `ctx.db.receipt()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.receipt().on_insert(...)`.
pub struct ReceiptTableHandle<'ctx> {
    imp: __sdk::TableHandle<Receipt>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `receipt`.
pub struct ReceiptTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ReceiptTableAccessor {
    type Row = Receipt;
    type Handle<'db> = ReceiptTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.receipt()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `receipt`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ReceiptTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ReceiptTableHandle`], which mediates access to the table `receipt`.
    fn receipt(&self) -> ReceiptTableHandle<'_>;
}

impl ReceiptTableAccess for super::RemoteTables {
    fn receipt(&self) -> ReceiptTableHandle<'_> {
        ReceiptTableHandle {
            imp: self.imp.get_table::<Receipt>("receipt"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ReceiptInsertCallbackId(__sdk::CallbackId);
pub struct ReceiptDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ReceiptTableHandle<'ctx> {
    type Row = Receipt;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Receipt> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for ReceiptTableHandle<'ctx> {
    type Row = Receipt;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Receipt> + '_ { self.imp.iter() }

    type InsertCallbackId = ReceiptInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReceiptInsertCallbackId {
        ReceiptInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ReceiptInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ReceiptDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReceiptDeleteCallbackId {
        ReceiptDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ReceiptDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ReceiptTableHandle<'ctx> {
    type InsertCallbackId = ReceiptInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReceiptInsertCallbackId {
        ReceiptInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ReceiptInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ReceiptTableHandle<'ctx> {
    type DeleteCallbackId = ReceiptDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReceiptDeleteCallbackId {
        ReceiptDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ReceiptDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ReceiptUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ReceiptTableHandle<'ctx> {
    type UpdateCallbackId = ReceiptUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ReceiptUpdateCallbackId {
        ReceiptUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ReceiptUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ReceiptTableHandle<'ctx> {
    type UpdateCallbackId = ReceiptUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ReceiptUpdateCallbackId {
        ReceiptUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ReceiptUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `receipt_id` unique index on the table `receipt`,
        /// which allows point queries on the field of the same name
        /// via the [`ReceiptReceiptIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.receipt().receipt_id().find(...)`.
        pub struct ReceiptReceiptIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Receipt, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ReceiptTableHandle<'ctx> {
            /// Get a handle on the `receipt_id` unique index on the table `receipt`.
            pub fn receipt_id(&self) -> ReceiptReceiptIdUnique<'ctx> {
                ReceiptReceiptIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("receipt_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ReceiptReceiptIdUnique<'ctx> {
            /// Find the subscribed row whose `receipt_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<Receipt> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Receipt>("receipt");
    _table.add_unique_constraint::<u64>("receipt_id", |row| &row.receipt_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Receipt>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Receipt>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Receipt`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait receiptQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Receipt`.
            fn receipt(&self) -> __sdk::__query_builder::Table<Receipt>;
        }

        impl receiptQueryTableAccess for __sdk::QueryTableAccessor {
            fn receipt(&self) -> __sdk::__query_builder::Table<Receipt> {
                __sdk::__query_builder::Table::new("receipt")
            }
        }

