// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Receipt {
    pub receipt_id: u64,
    pub store_name: String,
    pub purchased_at: i64,
    pub total: f64,
    pub tax: f64,
    pub currency: String,
    pub raw_ocr_text: String,
    pub image_url: String,
    pub added_by: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}


impl __sdk::InModule for Receipt {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Receipt`.
///
/// Provides typed access to columns for query building.
pub struct ReceiptCols {
    pub receipt_id: __sdk::__query_builder::Col<Receipt, u64>,
    pub store_name: __sdk::__query_builder::Col<Receipt, String>,
    pub purchased_at: __sdk::__query_builder::Col<Receipt, i64>,
    pub total: __sdk::__query_builder::Col<Receipt, f64>,
    pub tax: __sdk::__query_builder::Col<Receipt, f64>,
    pub currency: __sdk::__query_builder::Col<Receipt, String>,
    pub raw_ocr_text: __sdk::__query_builder::Col<Receipt, String>,
    pub image_url: __sdk::__query_builder::Col<Receipt, String>,
    pub added_by: __sdk::__query_builder::Col<Receipt, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<Receipt, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Receipt {
    type Cols = ReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ReceiptCols {
            receipt_id: __sdk::__query_builder::Col::new(table_name, "receipt_id"),
            store_name: __sdk::__query_builder::Col::new(table_name, "store_name"),
            purchased_at: __sdk::__query_builder::Col::new(table_name, "purchased_at"),
            total: __sdk::__query_builder::Col::new(table_name, "total"),
            tax: __sdk::__query_builder::Col::new(table_name, "tax"),
            currency: __sdk::__query_builder::Col::new(table_name, "currency"),
            raw_ocr_text: __sdk::__query_builder::Col::new(table_name, "raw_ocr_text"),
            image_url: __sdk::__query_builder::Col::new(table_name, "image_url"),
            added_by: __sdk::__query_builder::Col::new(table_name, "added_by"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),

        }
    }
}

/// Indexed column accessor struct for the table `Receipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct ReceiptIxCols {
    pub receipt_id: __sdk::__query_builder::IxCol<Receipt, u64>,
}

impl __sdk::__query_builder::HasIxCols for Receipt {
    type IxCols = ReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ReceiptIxCols {
            receipt_id: __sdk::__query_builder::IxCol::new(table_name, "receipt_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Receipt {}

