// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Recipe {
    pub recipe_id: u64,
    pub name: String,
    pub servings: u8,
    pub instructions: String,
    pub source_url: String,
    pub added_by: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}


impl __sdk::InModule for Recipe {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Recipe`.
///
/// Provides typed access to columns for query building.
pub struct RecipeCols {
    pub recipe_id: __sdk::__query_builder::Col<Recipe, u64>,
    pub name: __sdk::__query_builder::Col<Recipe, String>,
    pub servings: __sdk::__query_builder::Col<Recipe, u8>,
    pub instructions: __sdk::__query_builder::Col<Recipe, String>,
    pub source_url: __sdk::__query_builder::Col<Recipe, String>,
    pub added_by: __sdk::__query_builder::Col<Recipe, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<Recipe, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Recipe {
    type Cols = RecipeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RecipeCols {
            recipe_id: __sdk::__query_builder::Col::new(table_name, "recipe_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            servings: __sdk::__query_builder::Col::new(table_name, "servings"),
            instructions: __sdk::__query_builder::Col::new(table_name, "instructions"),
            source_url: __sdk::__query_builder::Col::new(table_name, "source_url"),
            added_by: __sdk::__query_builder::Col::new(table_name, "added_by"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),

        }
    }
}

/// Indexed column accessor struct for the table `Recipe`.
///
/// Provides typed access to indexed columns for query building.
pub struct RecipeIxCols {
    pub recipe_id: __sdk::__query_builder::IxCol<Recipe, u64>,
}

impl __sdk::__query_builder::HasIxCols for Recipe {
    type IxCols = RecipeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RecipeIxCols {
            recipe_id: __sdk::__query_builder::IxCol::new(table_name, "recipe_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Recipe {}

