// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubscribeDigestArgs {
    pub channel: String,
    pub handle: String,
}

impl From<SubscribeDigestArgs> for super::Reducer {
    fn from(args: SubscribeDigestArgs) -> Self {
        Self::SubscribeDigest {
            channel: args.channel,
            handle: args.handle,
}
}
}

impl __sdk::InModule for SubscribeDigestArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `subscribe_digest`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait subscribe_digest {
    /// Request that the remote module invoke the reducer `subscribe_digest` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`subscribe_digest:subscribe_digest_then`] to run a callback after the reducer completes.
    fn subscribe_digest(&self, channel: String,
handle: String,
) -> __sdk::Result<()> {
        self.subscribe_digest_then(channel, handle,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `subscribe_digest` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn subscribe_digest_then(
        &self,
        channel: String,
handle: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl subscribe_digest for super::RemoteReducers {
    fn subscribe_digest_then(
        &self,
        channel: String,
handle: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SubscribeDigestArgs { channel, handle,  }, callback)
    }
}

