// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  storeName: __t.string(),
  purchasedAt: __t.i64(),
  total: __t.f64(),
  tax: __t.f64(),
  currency: __t.string(),
  rawOcrText: __t.string(),
  imageUrl: __t.string(),
};
