// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  Location,
} from "./types";

export default {
  name: __t.string(),
  displayName: __t.string(),
  quantity: __t.f64(),
  unit: __t.string(),
  get location() {
    return Location;
  },
  estExpiryTs: __t.i64(),
  unopenedDays: __t.i32(),
  openedDays: __t.i32(),
  price: __t.f64(),
  currency: __t.string(),
  barcode: __t.string(),
  sourceReceiptId: __t.u64(),
};
