// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  outboxId: __t.u64().primaryKey().name("outbox_id"),
  subscriptionId: __t.u64().name("subscription_id"),
  channel: __t.string(),
  handle: __t.string(),
  message: __t.string(),
  itemCount: __t.u32().name("item_count"),
  isDelivered: __t.bool().name("is_delivered"),
  createdAt: __t.timestamp().name("created_at"),
});
