// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  subscriptionId: __t.u64().primaryKey().name("subscription_id"),
  identity: __t.identity(),
  channel: __t.string(),
  handle: __t.string(),
  isActive: __t.bool().name("is_active"),
  subscribedAt: __t.i64().name("subscribed_at"),
});
