// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ingestId: __t.u64().primaryKey().name("ingest_id"),
  kind: __t.string(),
  payload: __t.string(),
  submittedBy: __t.identity().name("submitted_by"),
  isProcessed: __t.bool().name("is_processed"),
  lastError: __t.string().name("last_error"),
  createdAt: __t.timestamp().name("created_at"),
  processedAt: __t.i64().name("processed_at"),
});
