// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Location,
  ItemStatus,
} from "./types";


export default __t.row({
  itemId: __t.u64().primaryKey().name("item_id"),
  name: __t.string(),
  displayName: __t.string().name("display_name"),
  barcode: __t.string(),
  quantity: __t.f64(),
  unit: __t.string(),
  get location() {
    return Location;
  },
  get status() {
    return ItemStatus;
  },
  estExpiryTs: __t.i64().name("est_expiry_ts"),
  unopenedDays: __t.i32().name("unopened_days"),
  openedDays: __t.i32().name("opened_days"),
  price: __t.f64(),
  currency: __t.string(),
  sourceReceiptId: __t.u64().name("source_receipt_id"),
  addedBy: __t.identity().name("added_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
