// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  receiptItemId: __t.u64().primaryKey().name("receipt_item_id"),
  receiptId: __t.u64().name("receipt_id"),
  productName: __t.string().name("product_name"),
  quantity: __t.f64(),
  unit: __t.string(),
  price: __t.f64(),
  currency: __t.string(),
  matchedItemId: __t.u64().name("matched_item_id"),
});
