// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  receiptId: __t.u64().primaryKey().name("receipt_id"),
  storeName: __t.string().name("store_name"),
  purchasedAt: __t.i64().name("purchased_at"),
  total: __t.f64(),
  tax: __t.f64(),
  currency: __t.string(),
  rawOcrText: __t.string().name("raw_ocr_text"),
  imageUrl: __t.string().name("image_url"),
  addedBy: __t.identity().name("added_by"),
  createdAt: __t.timestamp().name("created_at"),
});
