// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  recipeIngredientId: __t.u64().primaryKey().name("recipe_ingredient_id"),
  recipeId: __t.u64().name("recipe_id"),
  ingredientName: __t.string().name("ingredient_name"),
  quantity: __t.f64(),
  unit: __t.string(),
  isOptional: __t.bool().name("is_optional"),
  substitute: __t.string(),
});
