// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  recipeId: __t.u64().primaryKey().name("recipe_id"),
  name: __t.string(),
  servings: __t.u8(),
  instructions: __t.string(),
  sourceUrl: __t.string().name("source_url"),
  addedBy: __t.identity().name("added_by"),
  createdAt: __t.timestamp().name("created_at"),
});
