// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DigestOutbox = __t.object("DigestOutbox", {
  outboxId: __t.u64(),
  subscriptionId: __t.u64(),
  channel: __t.string(),
  handle: __t.string(),
  message: __t.string(),
  itemCount: __t.u32(),
  isDelivered: __t.bool(),
  createdAt: __t.timestamp(),
});
export type DigestOutbox = __Infer<typeof DigestOutbox>;

export const DigestSchedule = __t.object("DigestSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DigestSchedule = __Infer<typeof DigestSchedule>;

export const DigestSubscription = __t.object("DigestSubscription", {
  subscriptionId: __t.u64(),
  identity: __t.identity(),
  channel: __t.string(),
  handle: __t.string(),
  isActive: __t.bool(),
  subscribedAt: __t.i64(),
});
export type DigestSubscription = __Infer<typeof DigestSubscription>;

export const ExpirySweepSchedule = __t.object("ExpirySweepSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ExpirySweepSchedule = __Infer<typeof ExpirySweepSchedule>;

export const IngestInbox = __t.object("IngestInbox", {
  ingestId: __t.u64(),
  kind: __t.string(),
  payload: __t.string(),
  submittedBy: __t.identity(),
  isProcessed: __t.bool(),
  lastError: __t.string(),
  createdAt: __t.timestamp(),
  processedAt: __t.i64(),
});
export type IngestInbox = __Infer<typeof IngestInbox>;

export const Item = __t.object("Item", {
  itemId: __t.u64(),
  name: __t.string(),
  displayName: __t.string(),
  barcode: __t.string(),
  quantity: __t.f64(),
  unit: __t.string(),
  get location() {
    return Location;
  },
  get status() {
    return ItemStatus;
  },
  estExpiryTs: __t.i64(),
  unopenedDays: __t.i32(),
  openedDays: __t.i32(),
  price: __t.f64(),
  currency: __t.string(),
  sourceReceiptId: __t.u64(),
  addedBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Item = __Infer<typeof Item>;

// The tagged union or sum type for the algebraic type `ItemStatus`.
export const ItemStatus = __t.enum("ItemStatus", {
  Unopened: __t.unit(),
  Opened: __t.unit(),
  ExpiringSoon: __t.unit(),
  Depleted: __t.unit(),
});
export type ItemStatus = __Infer<typeof ItemStatus>;

// The tagged union or sum type for the algebraic type `Location`.
export const Location = __t.enum("Location", {
  Fridge: __t.unit(),
  Freezer: __t.unit(),
  Pantry: __t.unit(),
  Counter: __t.unit(),
  Other: __t.unit(),
});
export type Location = __Infer<typeof Location>;

export const PantryEvent = __t.object("PantryEvent", {
  eventId: __t.u64(),
  eventType: __t.string(),
  itemId: __t.u64(),
  description: __t.string(),
  actor: __t.identity(),
  createdAt: __t.timestamp(),
});
export type PantryEvent = __Infer<typeof PantryEvent>;

export const Receipt = __t.object("Receipt", {
  receiptId: __t.u64(),
  storeName: __t.string(),
  purchasedAt: __t.i64(),
  total: __t.f64(),
  tax: __t.f64(),
  currency: __t.string(),
  rawOcrText: __t.string(),
  imageUrl: __t.string(),
  addedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Receipt = __Infer<typeof Receipt>;

export const ReceiptItem = __t.object("ReceiptItem", {
  receiptItemId: __t.u64(),
  receiptId: __t.u64(),
  productName: __t.string(),
  quantity: __t.f64(),
  unit: __t.string(),
  price: __t.f64(),
  currency: __t.string(),
  matchedItemId: __t.u64(),
});
export type ReceiptItem = __Infer<typeof ReceiptItem>;

export const Recipe = __t.object("Recipe", {
  recipeId: __t.u64(),
  name: __t.string(),
  servings: __t.u8(),
  instructions: __t.string(),
  sourceUrl: __t.string(),
  addedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Recipe = __Infer<typeof Recipe>;

export const RecipeIngredient = __t.object("RecipeIngredient", {
  recipeIngredientId: __t.u64(),
  recipeId: __t.u64(),
  ingredientName: __t.string(),
  quantity: __t.f64(),
  unit: __t.string(),
  isOptional: __t.bool(),
  substitute: __t.string(),
});
export type RecipeIngredient = __Infer<typeof RecipeIngredient>;

export const ShoppingListItem = __t.object("ShoppingListItem", {
  shoppingItemId: __t.u64(),
  name: __t.string(),
  quantity: __t.f64(),
  unit: __t.string(),
  isStaple: __t.bool(),
  reason: __t.string(),
  addedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type ShoppingListItem = __Infer<typeof ShoppingListItem>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
  isActive: __t.bool(),
});
export type User = __Infer<typeof User>;

