// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddReceiptArgs {
    pub store_name: String,
    pub purchased_at: i64,
    pub total: f64,
    pub tax: f64,
    pub currency: String,
    pub raw_ocr_text: String,
    pub image_url: String,
}

impl From<AddReceiptArgs> for super::Reducer {
    fn from(args: AddReceiptArgs) -> Self {
        Self::AddReceipt {
            store_name: args.store_name,
            purchased_at: args.purchased_at,
            total: args.total,
            tax: args.tax,
            currency: args.currency,
            raw_ocr_text: args.raw_ocr_text,
            image_url: args.image_url,
}
}
}

impl __sdk::InModule for AddReceiptArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_receipt`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_receipt {
    /// Request that the remote module invoke the reducer `add_receipt` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_receipt:add_receipt_then`] to run a callback after the reducer completes.
    fn add_receipt(&self, store_name: String,
purchased_at: i64,
total: f64,
tax: f64,
currency: String,
raw_ocr_text: String,
image_url: String,
) -> __sdk::Result<()> {
        self.add_receipt_then(store_name, purchased_at, total, tax, currency, raw_ocr_text, image_url,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_receipt` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_receipt_then(
        &self,
        store_name: String,
purchased_at: i64,
total: f64,
tax: f64,
currency: String,
raw_ocr_text: String,
image_url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_receipt for super::RemoteReducers {
    fn add_receipt_then(
        &self,
        store_name: String,
purchased_at: i64,
total: f64,
tax: f64,
currency: String,
raw_ocr_text: String,
image_url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AddReceiptArgs { store_name, purchased_at, total, tax, currency, raw_ocr_text, image_url,  }, callback)
    }
}

