// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::location_type::Location;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddItemArgs {
    pub name: String,
    pub display_name: String,
    pub quantity: f64,
    pub unit: String,
    pub location: Location,
    pub est_expiry_ts: i64,
    pub unopened_days: i32,
    pub opened_days: i32,
    pub price: f64,
    pub currency: String,
    pub barcode: String,
    pub source_receipt_id: u64,
}

impl From<AddItemArgs> for super::Reducer {
    fn from(args: AddItemArgs) -> Self {
        Self::AddItem {
            name: args.name,
            display_name: args.display_name,
            quantity: args.quantity,
            unit: args.unit,
            location: args.location,
            est_expiry_ts: args.est_expiry_ts,
            unopened_days: args.unopened_days,
            opened_days: args.opened_days,
            price: args.price,
            currency: args.currency,
            barcode: args.barcode,
            source_receipt_id: args.source_receipt_id,
}
}
}

impl __sdk::InModule for AddItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_item {
    /// Request that the remote module invoke the reducer `add_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_item:add_item_then`] to run a callback after the reducer completes.
    fn add_item(&self, name: String,
display_name: String,
quantity: f64,
unit: String,
location: Location,
est_expiry_ts: i64,
unopened_days: i32,
opened_days: i32,
price: f64,
currency: String,
barcode: String,
source_receipt_id: u64,
) -> __sdk::Result<()> {
        self.add_item_then(name, display_name, quantity, unit, location, est_expiry_ts, unopened_days, opened_days, price, currency, barcode, source_receipt_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_item_then(
        &self,
        name: String,
display_name: String,
quantity: f64,
unit: String,
location: Location,
est_expiry_ts: i64,
unopened_days: i32,
opened_days: i32,
price: f64,
currency: String,
barcode: String,
source_receipt_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_item for super::RemoteReducers {
    fn add_item_then(
        &self,
        name: String,
display_name: String,
quantity: f64,
unit: String,
location: Location,
est_expiry_ts: i64,
unopened_days: i32,
opened_days: i32,
price: f64,
currency: String,
barcode: String,
source_receipt_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AddItemArgs { name, display_name, quantity, unit, location, est_expiry_ts, unopened_days, opened_days, price, currency, barcode, source_receipt_id,  }, callback)
    }
}

