// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddRecipeArgs {
    pub name: String,
    pub servings: u8,
    pub instructions: String,
    pub source_url: String,
}

impl From<AddRecipeArgs> for super::Reducer {
    fn from(args: AddRecipeArgs) -> Self {
        Self::AddRecipe {
            name: args.name,
            servings: args.servings,
            instructions: args.instructions,
            source_url: args.source_url,
}
}
}

impl __sdk::InModule for AddRecipeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_recipe`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_recipe {
    /// Request that the remote module invoke the reducer `add_recipe` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_recipe:add_recipe_then`] to run a callback after the reducer completes.
    fn add_recipe(&self, name: String,
servings: u8,
instructions: String,
source_url: String,
) -> __sdk::Result<()> {
        self.add_recipe_then(name, servings, instructions, source_url,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_recipe` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_recipe_then(
        &self,
        name: String,
servings: u8,
instructions: String,
source_url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_recipe for super::RemoteReducers {
    fn add_recipe_then(
        &self,
        name: String,
servings: u8,
instructions: String,
source_url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AddRecipeArgs { name, servings, instructions, source_url,  }, callback)
    }
}

