// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentHeartbeat {
    pub agent_name: String,
    pub last_seen_at: i64,
    pub state: String,
    pub updated_at: __sdk::Timestamp,
}


impl __sdk::InModule for AgentHeartbeat {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `AgentHeartbeat`.
///
/// Provides typed access to columns for query building.
pub struct AgentHeartbeatCols {
    pub agent_name: __sdk::__query_builder::Col<AgentHeartbeat, String>,
    pub last_seen_at: __sdk::__query_builder::Col<AgentHeartbeat, i64>,
    pub state: __sdk::__query_builder::Col<AgentHeartbeat, String>,
    pub updated_at: __sdk::__query_builder::Col<AgentHeartbeat, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AgentHeartbeat {
    type Cols = AgentHeartbeatCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentHeartbeatCols {
            agent_name: __sdk::__query_builder::Col::new(table_name, "agent_name"),
            last_seen_at: __sdk::__query_builder::Col::new(table_name, "last_seen_at"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),

        }
    }
}

/// Indexed column accessor struct for the table `AgentHeartbeat`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentHeartbeatIxCols {
    pub agent_name: __sdk::__query_builder::IxCol<AgentHeartbeat, String>,
}

impl __sdk::__query_builder::HasIxCols for AgentHeartbeat {
    type IxCols = AgentHeartbeatIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentHeartbeatIxCols {
            agent_name: __sdk::__query_builder::IxCol::new(table_name, "agent_name"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentHeartbeat {}

