// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::agent_heartbeat_type::AgentHeartbeat;

/// Table handle for the table `agent_heartbeats`.
///
/// Obtain a handle from the [`AgentHeartbeatsTableAccess::agent_heartbeats`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_heartbeats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_heartbeats().on_insert(...)`.
pub struct AgentHeartbeatsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentHeartbeat>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `agent_heartbeats`.
pub struct AgentHeartbeatsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AgentHeartbeatsTableAccessor {
    type Row = AgentHeartbeat;
    type Handle<'db> = AgentHeartbeatsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.agent_heartbeats()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_heartbeats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentHeartbeatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentHeartbeatsTableHandle`], which mediates access to the table `agent_heartbeats`.
    fn agent_heartbeats(&self) -> AgentHeartbeatsTableHandle<'_>;
}

impl AgentHeartbeatsTableAccess for super::RemoteTables {
    fn agent_heartbeats(&self) -> AgentHeartbeatsTableHandle<'_> {
        AgentHeartbeatsTableHandle {
            imp: self.imp.get_table::<AgentHeartbeat>("agent_heartbeats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentHeartbeatsInsertCallbackId(__sdk::CallbackId);
pub struct AgentHeartbeatsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AgentHeartbeatsTableHandle<'ctx> {
    type Row = AgentHeartbeat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = AgentHeartbeat> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for AgentHeartbeatsTableHandle<'ctx> {
    type Row = AgentHeartbeat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = AgentHeartbeat> + '_ { self.imp.iter() }

    type InsertCallbackId = AgentHeartbeatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentHeartbeatsInsertCallbackId {
        AgentHeartbeatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentHeartbeatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentHeartbeatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentHeartbeatsDeleteCallbackId {
        AgentHeartbeatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentHeartbeatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AgentHeartbeatsTableHandle<'ctx> {
    type InsertCallbackId = AgentHeartbeatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentHeartbeatsInsertCallbackId {
        AgentHeartbeatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentHeartbeatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AgentHeartbeatsTableHandle<'ctx> {
    type DeleteCallbackId = AgentHeartbeatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentHeartbeatsDeleteCallbackId {
        AgentHeartbeatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentHeartbeatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgentHeartbeatsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgentHeartbeatsTableHandle<'ctx> {
    type UpdateCallbackId = AgentHeartbeatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentHeartbeatsUpdateCallbackId {
        AgentHeartbeatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentHeartbeatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AgentHeartbeatsTableHandle<'ctx> {
    type UpdateCallbackId = AgentHeartbeatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentHeartbeatsUpdateCallbackId {
        AgentHeartbeatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentHeartbeatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `agent_name` unique index on the table `agent_heartbeats`,
        /// which allows point queries on the field of the same name
        /// via the [`AgentHeartbeatsAgentNameUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.agent_heartbeats().agent_name().find(...)`.
        pub struct AgentHeartbeatsAgentNameUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<AgentHeartbeat, String>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> AgentHeartbeatsTableHandle<'ctx> {
            /// Get a handle on the `agent_name` unique index on the table `agent_heartbeats`.
            pub fn agent_name(&self) -> AgentHeartbeatsAgentNameUnique<'ctx> {
                AgentHeartbeatsAgentNameUnique {
                    imp: self.imp.get_unique_constraint::<String>("agent_name"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> AgentHeartbeatsAgentNameUnique<'ctx> {
            /// Find the subscribed row whose `agent_name` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &String) -> Option<AgentHeartbeat> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<AgentHeartbeat>("agent_heartbeats");
    _table.add_unique_constraint::<String>("agent_name", |row| &row.agent_name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentHeartbeat>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<AgentHeartbeat>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `AgentHeartbeat`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait agent_heartbeatsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `AgentHeartbeat`.
            fn agent_heartbeats(&self) -> __sdk::__query_builder::Table<AgentHeartbeat>;
        }

        impl agent_heartbeatsQueryTableAccess for __sdk::QueryTableAccessor {
            fn agent_heartbeats(&self) -> __sdk::__query_builder::Table<AgentHeartbeat> {
                __sdk::__query_builder::Table::new("agent_heartbeats")
            }
        }

