// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DigestSubscription {
    pub subscription_id: u64,
    pub identity: __sdk::Identity,
    pub channel: String,
    pub handle: String,
    pub is_active: bool,
    pub subscribed_at: i64,
}


impl __sdk::InModule for DigestSubscription {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `DigestSubscription`.
///
/// Provides typed access to columns for query building.
pub struct DigestSubscriptionCols {
    pub subscription_id: __sdk::__query_builder::Col<DigestSubscription, u64>,
    pub identity: __sdk::__query_builder::Col<DigestSubscription, __sdk::Identity>,
    pub channel: __sdk::__query_builder::Col<DigestSubscription, String>,
    pub handle: __sdk::__query_builder::Col<DigestSubscription, String>,
    pub is_active: __sdk::__query_builder::Col<DigestSubscription, bool>,
    pub subscribed_at: __sdk::__query_builder::Col<DigestSubscription, i64>,
}

impl __sdk::__query_builder::HasCols for DigestSubscription {
    type Cols = DigestSubscriptionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DigestSubscriptionCols {
            subscription_id: __sdk::__query_builder::Col::new(table_name, "subscription_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            channel: __sdk::__query_builder::Col::new(table_name, "channel"),
            handle: __sdk::__query_builder::Col::new(table_name, "handle"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            subscribed_at: __sdk::__query_builder::Col::new(table_name, "subscribed_at"),

        }
    }
}

/// Indexed column accessor struct for the table `DigestSubscription`.
///
/// Provides typed access to indexed columns for query building.
pub struct DigestSubscriptionIxCols {
    pub subscription_id: __sdk::__query_builder::IxCol<DigestSubscription, u64>,
}

impl __sdk::__query_builder::HasIxCols for DigestSubscription {
    type IxCols = DigestSubscriptionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DigestSubscriptionIxCols {
            subscription_id: __sdk::__query_builder::IxCol::new(table_name, "subscription_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DigestSubscription {}

