// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::recipe_ingredient_type::RecipeIngredient;

/// Table handle for the table `recipe_ingredient`.
///
/// Obtain a handle from the [`RecipeIngredientTableAccess::recipe_ingredient`] method on [`super::RemoteTables`],
/// like `ctx.db.recipe_ingredient()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.recipe_ingredient().on_insert(...)`.
pub struct RecipeIngredientTableHandle<'ctx> {
    imp: __sdk::TableHandle<RecipeIngredient>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `recipe_ingredient`.
pub struct RecipeIngredientTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RecipeIngredientTableAccessor {
    type Row = RecipeIngredient;
    type Handle<'db> = RecipeIngredientTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.recipe_ingredient()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `recipe_ingredient`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RecipeIngredientTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RecipeIngredientTableHandle`], which mediates access to the table `recipe_ingredient`.
    fn recipe_ingredient(&self) -> RecipeIngredientTableHandle<'_>;
}

impl RecipeIngredientTableAccess for super::RemoteTables {
    fn recipe_ingredient(&self) -> RecipeIngredientTableHandle<'_> {
        RecipeIngredientTableHandle {
            imp: self.imp.get_table::<RecipeIngredient>("recipe_ingredient"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RecipeIngredientInsertCallbackId(__sdk::CallbackId);
pub struct RecipeIngredientDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RecipeIngredientTableHandle<'ctx> {
    type Row = RecipeIngredient;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = RecipeIngredient> + '_ { self.imp.iter() }
}

impl<'ctx> __sdk::Table for RecipeIngredientTableHandle<'ctx> {
    type Row = RecipeIngredient;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = RecipeIngredient> + '_ { self.imp.iter() }

    type InsertCallbackId = RecipeIngredientInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeIngredientInsertCallbackId {
        RecipeIngredientInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RecipeIngredientInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RecipeIngredientDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeIngredientDeleteCallbackId {
        RecipeIngredientDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RecipeIngredientDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RecipeIngredientTableHandle<'ctx> {
    type InsertCallbackId = RecipeIngredientInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeIngredientInsertCallbackId {
        RecipeIngredientInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RecipeIngredientInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RecipeIngredientTableHandle<'ctx> {
    type DeleteCallbackId = RecipeIngredientDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeIngredientDeleteCallbackId {
        RecipeIngredientDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RecipeIngredientDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RecipeIngredientUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RecipeIngredientTableHandle<'ctx> {
    type UpdateCallbackId = RecipeIngredientUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RecipeIngredientUpdateCallbackId {
        RecipeIngredientUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RecipeIngredientUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RecipeIngredientTableHandle<'ctx> {
    type UpdateCallbackId = RecipeIngredientUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RecipeIngredientUpdateCallbackId {
        RecipeIngredientUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RecipeIngredientUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `recipe_ingredient_id` unique index on the table `recipe_ingredient`,
        /// which allows point queries on the field of the same name
        /// via the [`RecipeIngredientRecipeIngredientIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.recipe_ingredient().recipe_ingredient_id().find(...)`.
        pub struct RecipeIngredientRecipeIngredientIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<RecipeIngredient, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> RecipeIngredientTableHandle<'ctx> {
            /// Get a handle on the `recipe_ingredient_id` unique index on the table `recipe_ingredient`.
            pub fn recipe_ingredient_id(&self) -> RecipeIngredientRecipeIngredientIdUnique<'ctx> {
                RecipeIngredientRecipeIngredientIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("recipe_ingredient_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> RecipeIngredientRecipeIngredientIdUnique<'ctx> {
            /// Find the subscribed row whose `recipe_ingredient_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<RecipeIngredient> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<RecipeIngredient>("recipe_ingredient");
    _table.add_unique_constraint::<u64>("recipe_ingredient_id", |row| &row.recipe_ingredient_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RecipeIngredient>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<RecipeIngredient>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `RecipeIngredient`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait recipe_ingredientQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `RecipeIngredient`.
            fn recipe_ingredient(&self) -> __sdk::__query_builder::Table<RecipeIngredient>;
        }

        impl recipe_ingredientQueryTableAccess for __sdk::QueryTableAccessor {
            fn recipe_ingredient(&self) -> __sdk::__query_builder::Table<RecipeIngredient> {
                __sdk::__query_builder::Table::new("recipe_ingredient")
            }
        }

