// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveShoppingItemArgs {
    pub shopping_item_id: u64,
}

impl From<RemoveShoppingItemArgs> for super::Reducer {
    fn from(args: RemoveShoppingItemArgs) -> Self {
        Self::RemoveShoppingItem {
            shopping_item_id: args.shopping_item_id,
}
}
}

impl __sdk::InModule for RemoveShoppingItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_shopping_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_shopping_item {
    /// Request that the remote module invoke the reducer `remove_shopping_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`remove_shopping_item:remove_shopping_item_then`] to run a callback after the reducer completes.
    fn remove_shopping_item(&self, shopping_item_id: u64,
) -> __sdk::Result<()> {
        self.remove_shopping_item_then(shopping_item_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `remove_shopping_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn remove_shopping_item_then(
        &self,
        shopping_item_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl remove_shopping_item for super::RemoteReducers {
    fn remove_shopping_item_then(
        &self,
        shopping_item_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(RemoveShoppingItemArgs { shopping_item_id,  }, callback)
    }
}

